import type { AnnuaireEnterprise } from './annuaire-data';
const S={
  tech:{id:'sec-01',name:"Technologies de l'Information",slug:'technologies',icon:'💻'},
  agri:{id:'sec-02',name:'Agriculture & Agroalimentaire',slug:'agriculture',icon:'🌾'},
  mines:{id:'sec-03',name:'Mines & Hydrocarbures',slug:'mines',icon:'⛏️'},
  trans:{id:'sec-04',name:'Transport & Logistique',slug:'transport',icon:'🚛'},
  bois:{id:'sec-05',name:'Bois & Forêt',slug:'bois',icon:'🌳'},
  sante:{id:'sec-06',name:'Santé & Pharmacie',slug:'sante',icon:'🏥'},
  educ:{id:'sec-07',name:'Éducation & Formation',slug:'education',icon:'🎓'},
  ener:{id:'sec-08',name:'Énergie & Environnement',slug:'energie',icon:'⚡'},
  btp:{id:'sec-09',name:'BTP & Immobilier',slug:'btp',icon:'🏗️'},
  comm:{id:'sec-10',name:'Commerce & Distribution',slug:'commerce',icon:'🛒'},
  tour:{id:'sec-11',name:'Tourisme & Hôtellerie',slug:'tourisme',icon:'🏨'},
  fin:{id:'sec-12',name:'Services Financiers',slug:'finance',icon:'🏦'},
} as const;
type E=[string,string,string,string,string,number,number,string,string[],boolean?];
function mk(e:E,i:number):AnnuaireEnterprise{
  const[n,sk,c,p,lf,y,em,d,t,digi]=e;const s=S[sk as keyof typeof S];
  const sl=n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);
  const x=String(i+1100).padStart(4,'0');
  return{id:`b4-${sl}`,rccm:`GA-LIB-${y}-D-${x}`,nif:`NIF-GA-${y}-${x}`,name:n,
    legalForm:lf as AnnuaireEnterprise['legalForm'],sector:s,status:'ACTIVE',
    address:{street:c,city:c,province:p,country:'Gabon'},
    description:d,employeeCount:em,yearFounded:y,isDigitalEcosystem:digi||false,
    tags:t,publicStats:{},createdAt:`${y}-01-01`,updatedAt:'2026-03-01'};
}
const D:E[]=[
  // ═══ OWENDO (Zone industrielle/portuaire) ═══
  ['Port d\'Owendo','trans','Owendo','Estuaire','SA',1974,500,'Port principal du Gabon.',['port','maritime']],
  ['CIMGABON - Cimenterie du Gabon','btp','Owendo','Estuaire','SA',2000,200,'Production de ciment Portland.',['ciment','production']],
  ['Olam Fertilisants Owendo','agri','Owendo','Estuaire','SA',2015,80,'Production d\'engrais.',['engrais','fertilisants']],
  ['Zone Industrielle d\'Owendo (ZIO)','comm','Owendo','Estuaire','SA',2005,30,'Gestion zone industrielle.',['industriel','zone']],
  ['SIGEPRAG','trans','Owendo','Estuaire','SA',2008,100,'Gestion portuaire.',['port','gestion']],
  ['SGA - Société Gabonaise d\'Acconage','trans','Owendo','Estuaire','SA',1990,150,'Manutention et acconage portuaire.',['acconage','manutention']],
  ['Terminal à Conteneurs d\'Owendo','trans','Owendo','Estuaire','SA',2012,200,'Gestion de conteneurs.',['conteneurs','terminal']],
  ['SOGARA Distribution','ener','Owendo','Estuaire','SA',2005,80,'Distribution de produits pétroliers.',['pétrole','distribution']],
  ['Dépôt Pétrolier d\'Owendo','ener','Owendo','Estuaire','SA',2000,40,'Stockage hydrocarbures.',['stockage','pétrole']],
  // ═══ NKOK (Zone Économique Spéciale) ═══
  ['GSEZ SA','comm','Nkok','Estuaire','SA',2010,300,'Gestionnaire Zone Économique Spéciale.',['GSEZ','zone spéciale']],
  ['Woodshow Gabon','bois','Nkok','Estuaire','SARL',2016,25,'Meubles en bois local.',['meubles','bois']],
  ['Gabon Timber Hub','bois','Nkok','Estuaire','SA',2014,50,'Plateforme bois GSEZ.',['plateforme','bois']],
  ['Panneaux du Gabon','bois','Nkok','Estuaire','SA',2015,60,'Panneaux de particules.',['panneaux','particules']],
  ['Mélamine Gabon','bois','Nkok','Estuaire','SARL',2017,30,'Stratifié et mélamine.',['mélamine','stratifié']],
  ['GSEZ Energie','ener','Nkok','Estuaire','SA',2012,40,'Production d\'énergie pour la ZES.',['énergie','ZES']],
  ['Asia Timber Export','bois','Nkok','Estuaire','SA',2015,45,'Export de bois transformé vers l\'Asie.',['export','Asie']],
  ['Quality Plywood Gabon','bois','Nkok','Estuaire','SARL',2018,35,'Contreplaqué haute qualité.',['contreplaqué','qualité']],
  ['NKOK Furniture','bois','Nkok','Estuaire','SARL',2019,20,'Fabrication de mobilier.',['mobilier','fabrication']],
  // ═══ SERVICES PROFESSIONNELS LIBREVILLE ═══
  ['Deloitte Gabon','fin','Libreville','Estuaire','SA',2005,50,'Audit, tax, consulting.',['audit','consulting']],
  ['PwC Gabon','fin','Libreville','Estuaire','SA',2000,60,'Audit et conseil.',['audit','PwC']],
  ['KPMG Gabon','fin','Libreville','Estuaire','SA',2002,45,'Audit, fiscalité, conseil.',['audit','KPMG']],
  ['Ernst & Young Gabon','fin','Libreville','Estuaire','SA',2005,40,'Audit et transactions.',['audit','EY']],
  ['Mazars Gabon','fin','Libreville','Estuaire','SARL',2010,20,'Audit et expertise comptable.',['audit','Mazars']],
  ['BDO Gabon','fin','Libreville','Estuaire','SARL',2012,15,'Audit et conseil.',['audit','BDO']],
  ['Fiduciaire d\'Afrique Centrale','fin','Libreville','Estuaire','SARL',2000,18,'Expertise comptable.',['comptable']],
  ['Cabinet d\'Expertise Mba-Owono','fin','Libreville','Estuaire','EI',2005,8,'Expertise comptable indépendant.',['comptable']],
  // ═══ COMMERCE — Stations service & Carburant ═══
  ['Total Gabon Distribution','comm','Libreville','Estuaire','SA',1990,200,'Réseau de stations-service Total.',['carburant','Total']],
  ['Engen Gabon','comm','Libreville','Estuaire','SA',2005,80,'Stations-service Engen.',['carburant','Engen']],
  ['Puma Energy Gabon','comm','Libreville','Estuaire','SA',2010,120,'Distribution de carburant.',['carburant','Puma']],
  ['Vivo Energy Gabon','comm','Libreville','Estuaire','SA',2012,100,'Distribution Shell au Gabon.',['carburant','Shell']],
  ['Oil Libya Gabon','comm','Libreville','Estuaire','SA',2008,60,'Stations-service et lubrifiants.',['carburant']],
  // ═══ COMMERCE — Concessionnaires auto ═══
  ['CFAO Motors Gabon','comm','Libreville','Estuaire','SA',1995,100,'Concessionnaire Toyota, Nissan.',['auto','Toyota']],
  ['Tractafric Motors Gabon','comm','Libreville','Estuaire','SA',2000,80,'Concessionnaire Mitsubishi, Hyundai.',['auto','Mitsubishi']],
  ['CFAO Equipment','comm','Libreville','Estuaire','SA',2005,60,'Engins et équipements Caterpillar.',['engins','Caterpillar']],
  ['Auto Gabon','comm','Libreville','Estuaire','SARL',2005,30,'Concessionnaire multi-marques.',['auto','concessionnaire']],
  ['Gabon Auto BMW','comm','Libreville','Estuaire','SARL',2010,20,'Concessionnaire BMW.',['auto','BMW']],
  ['Mercedes-Benz Gabon','comm','Libreville','Estuaire','SA',2008,25,'Concessionnaire Mercedes-Benz.',['auto','Mercedes']],
  ['Peugeot Gabon (STGA)','comm','Libreville','Estuaire','SA',2000,40,'Concessionnaire Peugeot.',['auto','Peugeot']],
  ['Renault Gabon','comm','Libreville','Estuaire','SARL',2005,30,'Concessionnaire Renault.',['auto','Renault']],
  // ═══ TOURISME — Agences de voyages & tours ═══
  ['Mistral Voyages Gabon','tour','Libreville','Estuaire','SARL',2000,15,'Agence de voyages premium.',['voyages','premium']],
  ['Gabon Découvertes','tour','Libreville','Estuaire','SARL',2010,8,'Circuits touristiques.',['circuits','tourisme']],
  ['Africa\'s Eden','tour','Libreville','Estuaire','SARL',2008,10,'Écotourisme national.',['écotourisme']],
  ['Tropicana Tours','tour','Libreville','Estuaire','SARL',2012,6,'Excursions et safaris.',['excursions','safaris']],
  ['Gabon Wildlife Camps','tour','Libreville','Estuaire','SARL',2015,8,'Camps de brousse et nature.',['camps','nature']],
  ['Air Services Gabon','trans','Libreville','Estuaire','SA',2010,20,'Vols charters et excursions.',['charter','aviation']],
  // ═══ SANTÉ — Laboratoires & équipements ═══
  ['Cermel - Centre de Recherche Médicale','sante','Lambaréné','Moyen-Ogooué','SA',2005,80,'Recherche médicale tropicale.',['recherche','tropical']],
  ['CIRMF Franceville','sante','Franceville','Haut-Ogooué','SA',1979,120,'Centre de recherche primatologie.',['recherche','primatologie']],
  ['Gabon Medical Supply','sante','Libreville','Estuaire','SARL',2010,15,'Fournitures et équipements médicaux.',['fournitures','médical']],
  ['Clinique de la Sécurité Sociale','sante','Libreville','Estuaire','SA',1975,100,'Clinique CNSS.',['clinique','CNSS']],
  ['Cabinet Radiologie Gabon','sante','Libreville','Estuaire','SARL',2010,10,'Radiologie et imagerie médicale.',['radiologie','imagerie']],
  ['Centre d\'Analyses Médicales','sante','Libreville','Estuaire','SARL',2005,12,'Analyses biologiques.',['analyses','biologie']],
  ['Clinique Dentaire Sourire','sante','Libreville','Estuaire','SARL',2012,8,'Soins dentaires et orthodontie.',['dentaire','orthodontie']],
  ['Médecins Sans Frontières Gabon','sante','Libreville','Estuaire','SA',1990,50,'ONG médicale.',['ONG','médical']],
  ['CNAMGS','sante','Libreville','Estuaire','SA',2008,200,'Caisse nationale d\'assurance maladie.',['assurance','maladie','CNAMGS']],
  ['CNSS Gabon','fin','Libreville','Estuaire','SA',1975,300,'Caisse nationale de sécurité sociale.',['sécurité sociale','CNSS']],
  // ═══ ÉDUCATION supplémentaire ═══
  ['École Internationale de Libreville','educ','Libreville','Estuaire','SA',2000,40,'École internationale multilingue.',['internationale']],
  ['Lycée National Léon Mba','educ','Libreville','Estuaire','SA',1965,80,'Lycée public historique.',['lycée','public']],
  ['Collège Bessieux','educ','Libreville','Estuaire','SA',1960,50,'Établissement catholique historique.',['catholique','collège']],
  ['École Gros Bouquet','educ','Libreville','Estuaire','SA',1980,30,'Établissement d\'enseignement.',['école']],
  ['Immaculée Conception Libreville','educ','Libreville','Estuaire','SA',1970,40,'Institution catholique.',['catholique']],
  ['Sainte-Marie Libreville','educ','Libreville','Estuaire','SA',1975,35,'École catholique de filles.',['catholique','filles']],
  ['École Américaine de Libreville','educ','Libreville','Estuaire','SARL',2005,25,'Programme américain K-12.',['américaine','international']],
  ['Formation Continue Gabon (FCG)','educ','Libreville','Estuaire','SARL',2010,10,'Formations professionnelles.',['formation','continue']],
  // ═══ TECH supplémentaire ═══
  ['Afriland First Digital','tech','Libreville','Estuaire','SARL',2020,8,'Fintech et services digitaux bancaires.',['fintech','digital'],true],
  ['GabonPay','tech','Libreville','Estuaire','SARL',2019,10,'Application de paiement mobile.',['paiement','mobile'],true],
  ['EduTech Gabon','tech','Libreville','Estuaire','SARL',2020,6,'Plateforme e-learning.',['e-learning','education'],true],
  ['HealthTech Gabon','tech','Libreville','Estuaire','SARL',2021,5,'Télémédecine et santé digitale.',['télémédecine','santé'],true],
  ['AgriTech Gabon','tech','Libreville','Estuaire','SARL',2020,8,'Solutions numériques agricoles.',['agriculture','numérique'],true],
  ['LogiTech Gabon','tech','Libreville','Estuaire','SARL',2019,7,'Solutions logistiques numériques.',['logistique','numérique'],true],
  ['CyberGabon','tech','Libreville','Estuaire','SARL',2017,12,'Solutions de cybersécurité.',['cybersécurité'],true],
  ['Gabon Digital Media','tech','Libreville','Estuaire','SARL',2018,8,'Production de contenu digital.',['contenu','digital'],true],
  // ═══ BTP supplémentaire ═══
  ['Béton Gabon','btp','Libreville','Estuaire','SA',2005,80,'Centrale à béton et préfabriqué.',['béton','préfabriqué']],
  ['Menuiserie Aluminium Gabon','btp','Libreville','Estuaire','SARL',2010,20,'Menuiserie alu et PVC.',['aluminium','PVC']],
  ['Serrurerie Gabon','btp','Libreville','Estuaire','SARL',2008,10,'Serrurerie et métallerie.',['serrurerie']],
  ['Isolation Thermique Gabon','btp','Libreville','Estuaire','SARL',2015,8,'Isolation et acoustique.',['isolation']],
  ['Terrassement Express','btp','Libreville','Estuaire','SARL',2010,25,'Terrassement et VRD.',['terrassement','VRD']],
  ['Démolition Gabon','btp','Libreville','Estuaire','SARL',2012,15,'Démolition et désamiantage.',['démolition']],
  // ═══ TRANSPORT supplémentaire ═══
  ['Gabon Airlines','trans','Libreville','Estuaire','SA',2006,80,'Compagnie aérienne nationale.',['aérien','national']],
  ['Chronopost Gabon','trans','Libreville','Estuaire','SARL',2010,15,'Livraison express colis.',['express','colis']],
  ['UPS Gabon','trans','Libreville','Estuaire','SA',2008,20,'Livraison colis international.',['UPS','international']],
  ['FedEx Gabon','trans','Libreville','Estuaire','SA',2005,15,'Courrier et colis express.',['FedEx','express']],
  ['Gabon Bus Rapid Transit','trans','Libreville','Estuaire','SA',2020,100,'Transport en commun BRT.',['BRT','bus']],
  // ═══ AGRICULTURE supplémentaire ═══
  ['SOGADEL Ntoum','agri','Ntoum','Estuaire','SA',2000,80,'Ferme avicole et bovine.',['aviculture','élevage']],
  ['Maïserie du Gabon','agri','Libreville','Estuaire','SA',2005,50,'Transformation du maïs.',['maïs','transformation']],
  ['Gabonaise de Chimie','agri','Libreville','Estuaire','SA',2010,40,'Engrais et produits chimiques.',['engrais','chimie']],
  ['Vivres du Gabon','agri','Libreville','Estuaire','SARL',2015,20,'Distribution alimentaire de gros.',['distribution','alimentaire']],
  ['Gabon Cocoa Trading','agri','Oyem','Woleu-Ntem','SARL',2012,15,'Négoce de cacao.',['cacao','négoce']],
  ['Palmeraies du Sud','agri','Tchibanga','Nyanga','SA',2008,100,'Huile de palme.',['palmier','huile']],
  // ═══ MINES supplémentaire ═══
  ['SGS Gabon (Inspection)','mines','Port-Gentil','Ogooué-Maritime','SA',1990,60,'Inspection, vérification, certification.',['inspection','certification']],
  ['Bureau Veritas Oil & Gas','mines','Port-Gentil','Ogooué-Maritime','SA',2000,50,'Certification secteur pétrolier.',['certification','pétrole']],
  ['Bourbon Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2005,120,'Services maritimes offshore.',['maritime','offshore']],
  ['Tidewater Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2000,80,'Navires de support offshore.',['navires','support']],
  ['VAALCO Production','mines','Port-Gentil','Ogooué-Maritime','SA',1998,100,'Production Etame.',['production','Etame']],
  ['Panoro Energy Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2015,40,'Exploration onshore.',['exploration']],
  // ═══ ÉNERGIE supplémentaire ═══
  ['Aggreko Gabon','ener','Libreville','Estuaire','SA',2010,30,'Location de groupes électrogènes.',['générateurs','location']],
  ['Total Lubricants Gabon','ener','Libreville','Estuaire','SA',2005,25,'Lubrifiants automobiles et industriels.',['lubrifiants']],
  ['GPL Gabon','ener','Libreville','Estuaire','SA',2008,20,'Distribution de gaz butane.',['gaz','butane']],
  ['Recyclage Gabon Vert','ener','Libreville','Estuaire','SARL',2018,12,'Recyclage et valorisation déchets.',['recyclage']],
  // ═══ COMMERCE supplémentaire ═══
  ['Fnac Gabon','comm','Libreville','Estuaire','SARL',2015,15,'Livres, multimédia, high-tech.',['multimédia','livres']],
  ['Bijouterie du Gabon','comm','Libreville','Estuaire','SARL',2005,6,'Bijouterie et horlogerie.',['bijouterie']],
  ['Optique Vision Plus','comm','Libreville','Estuaire','SARL',2010,8,'Lunettes et lentilles.',['optique']],
  ['Maroquinerie du Gabon','comm','Libreville','Estuaire','EI',2012,4,'Maroquinerie et accessoires.',['maroquinerie']],
  ['Parfumerie Élégance','comm','Libreville','Estuaire','SARL',2008,6,'Parfums et cosmétiques.',['parfums','cosmétiques']],
  ['Gabon Electronics','comm','Libreville','Estuaire','SARL',2015,10,'Installation TV, satellite, fibre.',['électronique','satellite']],
  ['Fournitures Bureau Gabon (FBG)','comm','Libreville','Estuaire','SARL',2005,12,'Fournitures de bureau.',['bureau','fournitures']],
  ['Papeterie Centrale Gabon','comm','Libreville','Estuaire','SARL',2000,10,'Papeterie et impressions.',['papeterie']],
  ['Magasin Sport Gabon','comm','Libreville','Estuaire','SARL',2012,8,'Articles de sport.',['sport','articles']],
  ['Piscines du Gabon','comm','Libreville','Estuaire','SARL',2010,6,'Construction et entretien piscines.',['piscines']],
  // ═══ TOURISME supplémentaire ═══
  ['Hôtel Atlantique','tour','Libreville','Estuaire','SA',2005,50,'Hôtel centre-ville Libreville.',['hôtel']],
  ['Hôtel Dialogue','tour','Port-Gentil','Ogooué-Maritime','SARL',2008,25,'Hôtel d\'affaires.',['hôtel']],
  ['La Cigale Hôtel','tour','Libreville','Estuaire','SARL',2010,20,'Hôtel charmant centre-ville.',['hôtel']],
  ['Résidence Le Plateau','tour','Libreville','Estuaire','SARL',2012,15,'Résidence hôtelière.',['résidence']],
  ['Airbnb Gabon Management','tour','Libreville','Estuaire','SARL',2018,5,'Gestion locations touristiques.',['location','Airbnb']],
  ['Restaurant La Dolce Vita','tour','Libreville','Estuaire','SARL',2015,10,'Restaurant italien.',['restaurant','italien']],
  ['Restaurant Le Jardin','tour','Libreville','Estuaire','SARL',2008,12,'Restaurant en plein air.',['restaurant','jardin']],
  ['Snack Bar Le Palmier','tour','Libreville','Estuaire','EI',2014,5,'Snack bar populaire.',['snack','bar']],
  ['Restaurant Gabon Grill','tour','Libreville','Estuaire','SARL',2016,8,'Grill et grillades.',['grill','restaurant']],
  // ═══ SERVICES supplémentaires ═══
  ['Gabon Informatique Services','tech','Libreville','Estuaire','SARL',2008,15,'Maintenance informatique.',['IT','maintenance'],true],
  ['Réseau Télécom Gabon','tech','Libreville','Estuaire','SA',2010,25,'Infrastructure réseau télécoms.',['réseau','infrastructure'],true],
  ['Agence Média Gabon','comm','Libreville','Estuaire','SARL',2012,10,'Agence médias et communication.',['médias']],
  ['Gabon Express Livraison','trans','Libreville','Estuaire','SARL',2019,15,'Livraison rapide e-commerce.',['livraison','e-commerce']],
  ['Société de Gardiennage du Gabon','comm','Libreville','Estuaire','SA',2005,200,'Gardiennage et surveillance.',['gardiennage']],
  ['Chrono Sécurité','comm','Libreville','Estuaire','SARL',2010,40,'Sécurité et protection.',['sécurité']],
  ['Agence Spéciale Gabon','comm','Libreville','Estuaire','SARL',2008,25,'Sécurité événementielle.',['sécurité','événement']],
  ['GASC - Group All Safe Conciergerie','comm','Libreville','Estuaire','SARL',2012,15,'Conciergerie et sécurité.',['conciergerie']],
  ['Nettoyage Pro Gabon','comm','Libreville','Estuaire','SARL',2015,30,'Nettoyage professionnel.',['nettoyage']],
  ['Gestion Immobilière du Gabon','btp','Libreville','Estuaire','SARL',2010,12,'Gestion locative et syndic.',['gestion','syndic']],
];
export const BATCH4_ENTERPRISES:AnnuaireEnterprise[]=D.map((e,i)=>mk(e,i));
