import type { AnnuaireEnterprise } from './annuaire-data';

const S = {
  tech: { id:'sec-01',name:"Technologies de l'Information",slug:'technologies',icon:'💻'},
  agri: { id:'sec-02',name:'Agriculture & Agroalimentaire',slug:'agriculture',icon:'🌾'},
  mines:{ id:'sec-03',name:'Mines & Hydrocarbures',slug:'mines',icon:'⛏️'},
  trans:{ id:'sec-04',name:'Transport & Logistique',slug:'transport',icon:'🚛'},
  bois: { id:'sec-05',name:'Bois & Forêt',slug:'bois',icon:'🌳'},
  sante:{ id:'sec-06',name:'Santé & Pharmacie',slug:'sante',icon:'🏥'},
  educ: { id:'sec-07',name:'Éducation & Formation',slug:'education',icon:'🎓'},
  ener: { id:'sec-08',name:'Énergie & Environnement',slug:'energie',icon:'⚡'},
  btp:  { id:'sec-09',name:'BTP & Immobilier',slug:'btp',icon:'🏗️'},
  comm: { id:'sec-10',name:'Commerce & Distribution',slug:'commerce',icon:'🛒'},
  tour: { id:'sec-11',name:'Tourisme & Hôtellerie',slug:'tourisme',icon:'🏨'},
  fin:  { id:'sec-12',name:'Services Financiers',slug:'finance',icon:'🏦'},
} as const;
type E=[string,string,string,string,string,number,number,string,string[],boolean?];
function b(e:E,i:number):AnnuaireEnterprise{
  const[n,sk,c,p,lf,y,em,d,t,isDigi]=e;
  const s=S[sk as keyof typeof S];
  const sl=n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);
  const x=String(i+500).padStart(4,'0');
  return{id:`b2-${sl}`,rccm:`GA-LIB-${y}-B-${x}`,nif:`NIF-GA-${y}-${x}`,name:n,
    legalForm:lf as AnnuaireEnterprise['legalForm'],sector:s,status:'ACTIVE',
    address:{street:c,city:c,province:p,country:'Gabon'},
    description:d,employeeCount:em,yearFounded:y,isDigitalEcosystem:isDigi||false,
    tags:t,publicStats:{},createdAt:`${y}-01-01`,updatedAt:'2026-03-01'};
}
const D:E[]=[
  // ══ PHARMACIES SUPPLÉMENTAIRES ══
  ['Pharmacie du Champ Triomphal','sante','Libreville','Estuaire','EI',2001,8,'Pharmacie au Champ Triomphal.',['pharmacie']],
  ['Pharmacie de Nzeng-Ayong','sante','Libreville','Estuaire','EI',2004,7,'Pharmacie quartier Nzeng-Ayong.',['pharmacie']],
  ['Pharmacie de la Peyrie','sante','Libreville','Estuaire','EI',2003,8,'Pharmacie de la Peyrie Libreville.',['pharmacie']],
  ['Pharmacie du Rond-Point','sante','Libreville','Estuaire','EI',2006,6,'Pharmacie de garde 24h.',['pharmacie','garde']],
  ['Pharmacie Okala','sante','Libreville','Estuaire','EI',2008,6,'Pharmacie à Okala.',['pharmacie']],
  ['Pharmacie Louis','sante','Libreville','Estuaire','EI',2005,7,'Pharmacie quartier Louis.',['pharmacie']],
  ['Pharmacie Owendo','sante','Owendo','Estuaire','EI',2007,6,'Pharmacie à Owendo.',['pharmacie']],
  ['Pharmacie Akébé','sante','Libreville','Estuaire','EI',2002,7,'Pharmacie quartier Akébé.',['pharmacie']],
  ['Pharmacie Glass','sante','Libreville','Estuaire','EI',2000,8,'Pharmacie au quartier Glass.',['pharmacie']],
  ['Pharmacie Nombakélé','sante','Libreville','Estuaire','EI',2009,6,'Pharmacie Nombakélé.',['pharmacie']],
  ['Pharmacie Mont-Bouët','sante','Libreville','Estuaire','EI',1998,9,'Pharmacie marché Mont-Bouët.',['pharmacie']],
  ['Pharmacie de Port-Gentil Centre','sante','Port-Gentil','Ogooué-Maritime','EI',2000,8,'Pharmacie centre-ville Port-Gentil.',['pharmacie']],
  ['Pharmacie Sogara','sante','Port-Gentil','Ogooué-Maritime','EI',2005,6,'Pharmacie quartier Sogara.',['pharmacie']],
  ['Pharmacie de Franceville','sante','Franceville','Haut-Ogooué','EI',1999,7,'Pharmacie centre Franceville.',['pharmacie']],
  ['Pharmacie de Moanda','sante','Moanda','Haut-Ogooué','EI',2003,5,'Pharmacie de Moanda.',['pharmacie']],
  ['Pharmacie de Mouila','sante','Mouila','Ngounié','EI',2006,5,'Pharmacie centre Mouila.',['pharmacie']],
  ['Pharmacie de Lambaréné','sante','Lambaréné','Moyen-Ogooué','EI',2004,6,'Pharmacie de Lambaréné.',['pharmacie']],
  ['Pharmacie d\'Oyem','sante','Oyem','Woleu-Ntem','EI',2005,5,'Pharmacie centre Oyem.',['pharmacie']],
  ['Pharmacie de Tchibanga','sante','Tchibanga','Nyanga','EI',2008,4,'Pharmacie de Tchibanga.',['pharmacie']],
  ['Pharmacie de Makokou','sante','Makokou','Ogooué-Ivindo','EI',2007,4,'Pharmacie de Makokou.',['pharmacie']],
  // ══ CLINIQUES & CENTRES MÉDICAUX ══
  ['Polyclinique El Rapha','sante','Libreville','Estuaire','SARL',2010,50,'Polyclinique privée multispécialités.',['polyclinique','privée']],
  ['Centre Médical de Nkembo','sante','Libreville','Estuaire','SARL',2008,25,'Centre médical quartier Nkembo.',['centre médical']],
  ['Cabinet Médical Oloumi','sante','Libreville','Estuaire','EI',2005,12,'Cabinet de consultations Oloumi.',['cabinet','médecine']],
  ['Laboratoire National de Santé Publique','sante','Libreville','Estuaire','SA',1995,80,'Analyses biomédicales et contrôle qualité.',['laboratoire','analyses']],
  ['Polyclinique Internationale de Libreville','sante','Libreville','Estuaire','SA',2012,100,'Polyclinique de standing international.',['polyclinique','international']],
  ['Centre Dentaire du Gabon','sante','Libreville','Estuaire','SARL',2010,15,'Soins dentaires et chirurgie buccale.',['dentaire','soins']],
  ['Clinique de Port-Gentil','sante','Port-Gentil','Ogooué-Maritime','SARL',2000,40,'Clinique privée à Port-Gentil.',['clinique','Port-Gentil']],
  ['Centre Hospitalier de Franceville','sante','Franceville','Haut-Ogooué','SA',1985,120,'Hôpital public de Franceville.',['hôpital','public']],
  // ══ HÔTELS & TOURISME SUPPLÉMENTAIRES ══
  ['Résidence Hôtelière du Phare','tour','Libreville','Estuaire','SARL',2013,20,'Résidence hôtelière bord de mer.',['résidence','hôtelière']],
  ['Hôtel Tropicana','tour','Libreville','Estuaire','SARL',2008,30,'Hôtel 3 étoiles au cœur de Libreville.',['hôtel','3 étoiles']],
  ['Hôtel La Baie des Rois','tour','Port-Gentil','Ogooué-Maritime','SA',2010,45,'Hôtel 4 étoiles face à la mer.',['hôtel','4 étoiles']],
  ['Hôtel Léconi Palace','tour','Franceville','Haut-Ogooué','SA',2000,60,'Hôtel de luxe à Franceville.',['hôtel','luxe']],
  ['Mbolo Beach Resort','tour','Libreville','Estuaire','SA',2018,35,'Resort balnéaire à Libreville.',['resort','plage']],
  ['Auberge de la Lopé','tour','Lopé','Ogooué-Ivindo','SARL',2005,15,'Écotourisme parc national de la Lopé.',['écotourisme','Lopé']],
  ['Hôtel Missier','tour','Port-Gentil','Ogooué-Maritime','SARL',2012,20,'Hôtel d\'affaires Port-Gentil.',['hôtel','affaires']],
  ['Lopé Hotel','tour','Lopé','Ogooué-Ivindo','SARL',2008,18,'Hôtel safari proche du parc.',['safari','Lopé']],
  ['Village Gauthier','tour','Libreville','Estuaire','SARL',2015,12,'Village de vacances familial.',['village vacances']],
  ['Complexe Touristique de Pointe-Denis','tour','Libreville','Estuaire','SA',2000,40,'Complexe balnéaire Pointe-Denis.',['balnéaire','Pointe-Denis']],
  ['Restaurant L\'Odika','tour','Libreville','Estuaire','EI',2016,10,'Restaurant gastronomique gabonais.',['restaurant','gabonais']],
  ['Restaurant Les Boucaniers','tour','Port-Gentil','Ogooué-Maritime','SARL',2010,12,'Fruits de mer et cuisine locale.',['restaurant','fruits de mer']],
  ['Restaurant Le Sunset','tour','Libreville','Estuaire','EI',2018,8,'Bar restaurant sur la plage.',['bar','restaurant']],
  ['Boulangerie Pâtisserie Rémy','tour','Libreville','Estuaire','EI',2005,15,'Boulangerie artisanale française.',['boulangerie','pâtisserie']],
  ['Pâtisserie La Gourmandise','tour','Libreville','Estuaire','EI',2012,10,'Pâtisserie et viennoiseries.',['pâtisserie']],
  ['Traiteur Saveurs du Gabon','tour','Libreville','Estuaire','SARL',2014,12,'Traiteur spécialisé cuisine gabonaise.',['traiteur','gabonais']],
  // ══ BTP & IMMOBILIER SUPPLÉMENTAIRES ══
  ['Eiffage Gabon','btp','Libreville','Estuaire','SA',1990,300,'Filiale du groupe Eiffage. Routes, bâtiment, génie civil.',['Eiffage','routes','génie civil']],
  ['Bouygues Bâtiment Gabon','btp','Libreville','Estuaire','SA',1985,250,'Grands travaux de bâtiment et infrastructure.',['Bouygues','bâtiment']],
  ['SETEG','btp','Libreville','Estuaire','SA',1988,150,'Société d\'études techniques et de génie civil.',['études','génie civil']],
  ['Entreprise Fougerolles Gabon','btp','Libreville','Estuaire','SA',1978,200,'Travaux publics et bâtiment.',['travaux publics']],
  ['GTR - Gabonaise de Travaux Routiers','btp','Libreville','Estuaire','SA',2000,120,'Construction et entretien de routes.',['routes','voirie']],
  ['SATOM Gabon','btp','Libreville','Estuaire','SA',1992,180,'Travaux routiers et terrassement.',['routes','terrassement']],
  ['Société Gabonaise de Promotion Immobilière','btp','Libreville','Estuaire','SA',2005,60,'Promotion immobilière résidentielle.',['promotion','résidentiel']],
  ['Agence Immobilière du Gabon','btp','Libreville','Estuaire','SARL',2008,20,'Transactions et gestion immobilière.',['immobilier','transactions']],
  ['GTI - Gabonaise de Travaux et d\'Ingénierie','btp','Libreville','Estuaire','SA',2010,100,'Ingénierie et grands travaux.',['ingénierie','travaux']],
  ['BET Gabon','btp','Libreville','Estuaire','SARL',2005,30,'Bureau d\'études techniques.',['études','BET']],
  ['Lafarge Ciments Gabon','btp','Libreville','Estuaire','SA',2002,120,'Production de ciment et matériaux.',['ciment','matériaux']],
  ['Point P Gabon','btp','Libreville','Estuaire','SARL',2010,50,'Distribution de matériaux de construction.',['matériaux','distribution']],
  ['SNBG Construction','btp','Libreville','Estuaire','SARL',2012,40,'Construction résidentielle et commerciale.',['construction']],
  ['Immobilière de l\'Estuaire','btp','Libreville','Estuaire','SARL',2015,15,'Agence immobilière Estuaire.',['immobilier','agence']],
  ['Afriland Construction Gabon','btp','Libreville','Estuaire','SA',2016,80,'Construction d\'immeubles et résidences.',['construction','résidentiel']],
  // ══ COMMERCE & DISTRIBUTION SUPPLÉMENTAIRES ══
  ['Gaboprix','comm','Libreville','Estuaire','SA',2010,100,'Chaîne de supermarchés discount.',['supermarché','discount']],
  ['Hyper U Libreville','comm','Libreville','Estuaire','SA',2015,80,'Hypermarché, enseigne française U.',['hypermarché','U']],
  ['Magasin King','comm','Libreville','Estuaire','SARL',2012,25,'Magasin de détail produits divers.',['détail','commerce']],
  ['Librairie Sogalivre','comm','Libreville','Estuaire','SARL',2000,15,'Librairie et papeterie de référence.',['librairie','papeterie']],
  ['Comptoir Gabonais du Commerce','comm','Libreville','Estuaire','SA',1975,150,'Import-export et distribution.',['import-export']],
  ['CECA-GADIS Gabon','comm','Libreville','Estuaire','SA',1980,180,'Distribution alimentaire en gros.',['distribution','alimentaire','gros']],
  ['ETS Haddad','comm','Libreville','Estuaire','SARL',1990,50,'Commerce général et import.',['commerce','import']],
  ['Mounana Commerce Général','comm','Mounana','Haut-Ogooué','SARL',2005,10,'Commerce général à Mounana.',['commerce']],
  ['Quincaillerie Centrale','comm','Libreville','Estuaire','SARL',1998,20,'Quincaillerie et outillage.',['quincaillerie','outillage']],
  ['Gabon Auto Parts','comm','Libreville','Estuaire','SARL',2008,25,'Pièces automobiles et accessoires.',['auto','pièces']],
  ['Électro Gabon','comm','Libreville','Estuaire','SARL',2010,18,'Électroménager et électronique.',['électronique','électroménager']],
  ['Boutique Mode Africaine','comm','Libreville','Estuaire','EI',2015,8,'Mode et prêt-à-porter africain.',['mode','africain']],
  ['Comptoir du Mobilier Gabon','comm','Libreville','Estuaire','SARL',2012,20,'Mobilier et décoration intérieure.',['mobilier','décoration']],
  ['Gabon Pièces Auto','comm','Port-Gentil','Ogooué-Maritime','SARL',2006,15,'Pièces détachées automobiles.',['auto','pièces']],
  ['Marché du Pneu Gabon','comm','Libreville','Estuaire','SARL',2009,12,'Pneumatiques et services auto.',['pneu','auto']],
  // ══ TRANSPORT SUPPLÉMENTAIRES ══
  ['Trans Express Gabon','trans','Libreville','Estuaire','SARL',2012,40,'Messagerie et transport express.',['express','messagerie']],
  ['Gabon Transit','trans','Libreville','Estuaire','SA',2005,60,'Transit et dédouanement.',['transit','douane']],
  ['OPRAG - Office des Ports et Rades du Gabon','trans','Libreville','Estuaire','SA',1974,400,'Gestion ports d\'Owendo et Port-Gentil.',['port','maritime']],
  ['ASECNA Gabon','trans','Libreville','Estuaire','SA',1960,250,'Sécurité de la navigation aérienne.',['aérien','sécurité','navigation']],
  ['Bolloré Transport Gabon','trans','Libreville','Estuaire','SA',1998,200,'Logistique intégrée et portuaire.',['logistique','Bolloré']],
  ['TNT Express Gabon','trans','Libreville','Estuaire','SARL',2008,25,'Courrier express international.',['express','courrier']],
  ['Taxi Service Plus','trans','Libreville','Estuaire','SARL',2015,30,'Service de taxi VTC.',['taxi','VTC']],
  ['Gabon Shipping','trans','Port-Gentil','Ogooué-Maritime','SA',2005,80,'Transport maritime et cabotage.',['maritime','cabotage']],
  ['Société Portuaire de Port-Gentil','trans','Port-Gentil','Ogooué-Maritime','SA',2008,100,'Opérations portuaires Port-Gentil.',['port','opérations']],
  ['AMG - Auto Moto Gabon','trans','Libreville','Estuaire','SARL',2010,20,'Location de véhicules et motos.',['location','véhicules']],
  // ══ AGRICULTURE SUPPLÉMENTAIRES ══
  ['SOGAPÊCHE','agri','Libreville','Estuaire','SA',1985,150,'Pêche industrielle et commerciale.',['pêche','industrielle']],
  ['Gabon Aquaculture','agri','Libreville','Estuaire','SARL',2016,30,'Aquaculture et pisciculture.',['aquaculture','pisciculture']],
  ['Palmier du Gabon','agri','Lambaréné','Moyen-Ogooué','SA',2010,200,'Plantations de palmier à huile.',['palmier','huile']],
  ['Riziculture du Gabon','agri','Tchibanga','Nyanga','SARL',2015,40,'Culture du riz local.',['riz','culture']],
  ['Élevage Moderne du Gabon','agri','Franceville','Haut-Ogooué','SARL',2012,35,'Élevage bovin et porcin.',['élevage','bovin']],
  ['Coopérative Agricole de Bitam','agri','Bitam','Woleu-Ntem','SCS',2010,20,'Coopérative agricole vivrière.',['coopérative','vivrier']],
  ['Société de Culture Bananière','agri','Libreville','Estuaire','SA',2005,80,'Production de bananes plantain.',['banane','plantain']],
  ['AGRIPOG - Agriculture Moderne Port-Gentil','agri','Port-Gentil','Ogooué-Maritime','SARL',2018,15,'Maraîchage urbain.',['maraîchage','urbain']],
  ['Ferme Avicole du Gabon','agri','Libreville','Estuaire','SARL',2014,25,'Production d\'œufs et poulets.',['aviculture','œufs']],
  ['Gabon Cacao','agri','Woleu-Ntem','Woleu-Ntem','SARL',2016,30,'Production et export de cacao.',['cacao','export']],
  ['Pêcheries de l\'Ogooué','agri','Lambaréné','Moyen-Ogooué','SARL',2008,20,'Pêche artisanale et transformation.',['pêche','artisanale']],
  ['Société des Plantations du Haut-Ogooué','agri','Franceville','Haut-Ogooué','SA',1990,250,'Plantations de canne à sucre et cultures.',['plantations','canne']],
  ['GabonVert','agri','Libreville','Estuaire','SARL',2020,10,'Agriculture bio et circuits courts.',['bio','circuits courts']],
  ['Société Gabonaise de Transformation Alimentaire','agri','Libreville','Estuaire','SA',2010,60,'Transformation de produits alimentaires.',['transformation','alimentaire']],
  ['IGAD Agri','agri','Libreville','Estuaire','SARL',2015,15,'Conseil agricole et formation.',['conseil','formation']],
  // ══ ÉNERGIE SUPPLÉMENTAIRES ══
  ['Gabon Oil Company (GOC)','ener','Libreville','Estuaire','SA',2006,150,'Société nationale pétrolière.',['pétrole','national']],
  ['Société d\'Énergie et d\'Eau du Gabon (SEEG)','ener','Libreville','Estuaire','SA',1950,2000,'Distribution eau et électricité nationale.',['eau','électricité','distribution']],
  ['CODER Gabon','ener','Libreville','Estuaire','SA',2010,40,'Énergies renouvelables et conseil.',['renouvelable','conseil']],
  ['Société des Eaux Minérales du Gabon','ener','Libreville','Estuaire','SA',2005,60,'Production d\'eau minérale.',['eau minérale','production']],
  ['Petro Gabon','ener','Port-Gentil','Ogooué-Maritime','SA',2000,80,'Distribution de produits pétroliers.',['distribution','pétrole']],
  ['Engie Gabon','ener','Libreville','Estuaire','SA',2015,50,'Solutions énergétiques industrielles.',['énergie','industriel']],
  ['Solar Gabon','ener','Libreville','Estuaire','SARL',2019,15,'Installation solaire photovoltaïque.',['solaire','photovoltaïque']],
  ['Bureau Veritas Gabon','ener','Libreville','Estuaire','SA',2000,40,'Certification et contrôle qualité.',['certification','contrôle']],
  // ══ ÉDUCATION SUPPLÉMENTAIRES ══
  ['École Normale Supérieure','educ','Libreville','Estuaire','SA',1972,80,'Formation des enseignants.',['enseignants','formation']],
  ['Université des Sciences de la Santé','educ','Owendo','Estuaire','SA',2002,200,'Formation médicale et paramédicale.',['médecine','santé']],
  ['ENSET - École Normale Supérieure de l\'Enseignement Technique','educ','Libreville','Estuaire','SA',1978,60,'Formation technique et professionnelle.',['technique','enseignement']],
  ['Institut de Géologie et Mines','educ','Franceville','Haut-Ogooué','SA',1990,50,'Formation en géologie et mines.',['géologie','mines']],
  ['Centre de Formation Professionnelle','educ','Libreville','Estuaire','SA',2005,30,'Formation professionnelle continue.',['formation','professionnel']],
  ['Institut Pédagogique National','educ','Libreville','Estuaire','SA',1985,40,'Pédagogie et innovation éducative.',['pédagogie','éducation']],
  ['Académie Internationale de l\'Aviation','educ','Libreville','Estuaire','SARL',2015,20,'Formation pilotes et personnel navigant.',['aviation','pilotes']],
  ['École Supérieure des Arts et Métiers','educ','Libreville','Estuaire','SA',2000,35,'Arts appliqués et métiers créatifs.',['arts','métiers']],
  ['CAMES Gabon','educ','Libreville','Estuaire','SA',1968,15,'Conseil africain pour l\'enseignement supérieur.',['enseignement supérieur']],
  ['Institut des Langues Vivantes','educ','Libreville','Estuaire','SARL',2010,12,'Formation en langues étrangères.',['langues','formation']],
  // ══ MINES SUPPLÉMENTAIRES ══
  ['Manganèse du Gabon (Manga)','mines','Moanda','Haut-Ogooué','SA',2014,180,'Extraction de manganèse.',['manganèse','extraction']],
  ['Gabon Gold','mines','Mitzic','Woleu-Ntem','SA',2018,60,'Exploration aurifère.',['or','exploration']],
  ['Ivindo Mining','mines','Makokou','Ogooué-Ivindo','SA',2016,40,'Exploration minière Ogooué-Ivindo.',['exploration','minière']],
  ['Société des Carrières du Gabon','mines','Libreville','Estuaire','SA',2000,80,'Exploitation de carrières et granulats.',['carrières','granulats']],
  ['Sino Gabon Mining','mines','Franceville','Haut-Ogooué','SA',2012,100,'Partenariat sino-gabonais mines.',['mines','Chine']],
  ['Gabon Marble','mines','Franceville','Haut-Ogooué','SARL',2015,25,'Extraction et taille de marbre.',['marbre','extraction']],
  ['Atlantic Petroleum Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2008,70,'Exploration offshore.',['pétrole','offshore']],
  ['Schlumberger Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1980,200,'Services pétroliers et parapétroliers.',['services pétroliers']],
  ['Halliburton Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1985,150,'Services de forage et complétion.',['forage','services']],
  ['Baker Hughes Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1990,120,'Technologies pétrolières.',['technologie','pétrole']],
  ['Weatherford Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1995,80,'Services de puits et production.',['puits','production']],
  ['CGG Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2000,60,'Études sismiques et géophysique.',['sismique','géophysique']],
  // ══ BOIS SUPPLÉMENTAIRES ══
  ['Rimbunan Hijau Gabon','bois','Libreville','Estuaire','SA',2002,250,'Exploitation forestière et sciage, groupe malaisien.',['Malaisie','exploitation']],
  ['Olam Wood Gabon','bois','Nkok','Estuaire','SA',2010,300,'Transformation bois GSEZ, placages.',['GSEZ','placages','Olam']],
  ['SFM - Société Forestière de Mékambo','bois','Mékambo','Ogooué-Ivindo','SA',2005,80,'Exploitation forestière Ogooué-Ivindo.',['exploitation','Mékambo']],
  ['EFM - Entreprise Forestière de Moanda','bois','Moanda','Haut-Ogooué','SARL',2008,50,'Exploitation forestière Moanda.',['exploitation','Moanda']],
  ['FBA - Forestière des Bois d\'Azingo','bois','Libreville','Estuaire','SA',2000,70,'Exploitation bois Azingo.',['exploitation','Azingo']],
  ['SUNLY Mouila','bois','Mouila','Ngounié','SA',2015,100,'Concession forestière Ngounié.',['concession','Ngounié']],
  ['SUNLY Okondja','bois','Okondja','Haut-Ogooué','SA',2016,80,'Concession forestière Okondja.',['concession','Okondja']],
  ['TLP - Tropical Logs Production','bois','Libreville','Estuaire','SARL',2012,40,'Production et export de grumes.',['grumes','export']],
  ['Philia International Gabon','bois','Libreville','Estuaire','SA',2010,60,'Commerce international de bois.',['international','commerce']],
  ['Naike Wood','bois','Libreville','Estuaire','SARL',2018,20,'Transformation locale de bois.',['transformation','local']],
  // ══ TECH & DIGITAL SUPPLÉMENTAIRES ══
  ['GabonTelecom (Moov Africa)','tech','Libreville','Estuaire','SA',1999,800,'Opérateur télécom historique national.',['télécom','mobile','fixe'],true],
  ['Airtel Gabon','tech','Libreville','Estuaire','SA',2000,600,'2ème opérateur mobile du Gabon.',['mobile','télécom'],true],
  ['MTN Gabon (ex-Libertis)','tech','Libreville','Estuaire','SA',2006,400,'Opérateur mobile, services data.',['mobile','data'],true],
  ['Gabonaise d\'Informatique','tech','Libreville','Estuaire','SARL',2005,30,'Services informatiques et maintenance.',['informatique','maintenance'],true],
  ['Cyber Secure Gabon','tech','Libreville','Estuaire','SARL',2018,15,'Cybersécurité et protection des données.',['cybersécurité','protection'],true],
  ['DataCenter Gabon','tech','Libreville','Estuaire','SA',2020,25,'Hébergement de données et cloud.',['datacenter','cloud'],true],
  ['Gabon Numerique SA','tech','Libreville','Estuaire','SA',2015,40,'Développement de solutions numériques.',['développement','numérique'],true],
  ['E-Gov Gabon Solutions','tech','Libreville','Estuaire','SARL',2017,20,'Solutions e-gouvernement.',['e-gov','administration'],true],
  ['TechPay Gabon','tech','Libreville','Estuaire','SARL',2019,12,'Solutions de paiement mobile.',['paiement','mobile','fintech'],true],
  ['CloudAfrica Gabon','tech','Libreville','Estuaire','SARL',2021,10,'Services cloud pour entreprises.',['cloud','SaaS'],true],
  // ══ SERVICES FINANCIERS SUPPLÉMENTAIRES ══
  ['BGFI Securities','fin','Libreville','Estuaire','SA',2005,30,'Courtage en valeurs mobilières.',['bourse','courtage']],
  ['Société Nationale d\'Assurances et de Réassurances','fin','Libreville','Estuaire','SA',2010,50,'Assurance et réassurance d\'État.',['assurance','réassurance']],
  ['PostBank Gabon','fin','Libreville','Estuaire','SA',2012,80,'Services bancaires postaux.',['banque','postale']],
  ['Banque de Développement du Gabon','fin','Libreville','Estuaire','SA',1960,100,'Financement du développement.',['développement','financement']],
  ['Caisse de Dépôts et Consignations','fin','Libreville','Estuaire','SA',2008,60,'Gestion de fonds publics.',['dépôts','public']],
  ['Crédit du Gabon','fin','Libreville','Estuaire','SA',1995,120,'Banque de crédit aux entreprises.',['crédit','entreprises']],
  ['Micro-Finance Gabonaise','fin','Libreville','Estuaire','SARL',2015,20,'Microfinance et épargne populaire.',['microfinance','épargne']],
  ['BEAC Libreville','fin','Libreville','Estuaire','SA',1972,150,'Banque centrale CEMAC au Gabon.',['banque centrale','CEMAC']],
  ['Western Union Gabon','fin','Libreville','Estuaire','SA',2000,15,'Transferts d\'argent internationaux.',['transferts','argent']],
  ['MoneyGram Gabon','fin','Libreville','Estuaire','SA',2005,10,'Transferts d\'argent.',['transferts','MoneyGram']],
  // ══ SERVICES DIVERS ══
  ['Gabon Télécom Services','comm','Libreville','Estuaire','SA',2010,30,'Maintenance réseaux télécoms.',['télécom','maintenance']],
  ['Imprimerie Multipress Gabon','comm','Libreville','Estuaire','SA',1990,40,'Imprimerie et édition.',['imprimerie','édition']],
  ['Publicité au Gabon (PUBLI GAB)','comm','Libreville','Estuaire','SARL',2005,20,'Agence de publicité et communication.',['publicité','communication']],
  ['Gabon Média System','comm','Libreville','Estuaire','SARL',2012,15,'Médias numériques et production.',['médias','production']],
  ['Société Gabonaise de Nettoyage','comm','Libreville','Estuaire','SARL',2008,100,'Nettoyage industriel et tertiaire.',['nettoyage','propreté']],
  ['Intérim Gabon','comm','Libreville','Estuaire','SARL',2010,30,'Travail temporaire et recrutement.',['intérim','recrutement']],
  ['ManPower Gabon','comm','Libreville','Estuaire','SA',2005,40,'Recrutement et ressources humaines.',['RH','recrutement']],
  ['Gabon Consulting Group','comm','Libreville','Estuaire','SARL',2012,15,'Cabinet de conseil en stratégie.',['conseil','stratégie']],
  ['Bureau d\'Études Ingénieurs Associés','comm','Libreville','Estuaire','SARL',2008,20,'Bureau d\'études pluridisciplinaire.',['études','ingénierie']],
  ['Africa Communications Gabon','comm','Libreville','Estuaire','SARL',2015,12,'Relations publiques et événementiel.',['RP','événementiel']],
  ['Société Gabonaise de Blanchisserie','comm','Libreville','Estuaire','SARL',2010,25,'Blanchisserie industrielle.',['blanchisserie','industriel']],
  ['déménagement Express Gabon','comm','Libreville','Estuaire','SARL',2014,15,'Déménagement et logistique.',['déménagement']],
  ['Gabon Events','comm','Libreville','Estuaire','SARL',2016,10,'Organisation d\'événements.',['événements','organisation']],
  ['Jardins du Gabon','comm','Libreville','Estuaire','SARL',2018,8,'Paysagisme et espaces verts.',['paysagisme','jardins']],
  ['Société de Location Automobile (SLA)','comm','Libreville','Estuaire','SARL',2005,25,'Location de véhicules.',['location','auto']],
  ['Gabon Press Services','comm','Libreville','Estuaire','SARL',2010,8,'Agence de presse locale.',['presse','médias']],
];
export const BATCH2_ENTERPRISES:AnnuaireEnterprise[]=D.map((e,i)=>b(e,i));
