import type { AnnuaireEnterprise } from './annuaire-data';
const S={
  tech:{id:'sec-01',name:"Technologies de l'Information",slug:'technologies',icon:'💻'},
  agri:{id:'sec-02',name:'Agriculture & Agroalimentaire',slug:'agriculture',icon:'🌾'},
  mines:{id:'sec-03',name:'Mines & Hydrocarbures',slug:'mines',icon:'⛏️'},
  trans:{id:'sec-04',name:'Transport & Logistique',slug:'transport',icon:'🚛'},
  bois:{id:'sec-05',name:'Bois & Forêt',slug:'bois',icon:'🌳'},
  sante:{id:'sec-06',name:'Santé & Pharmacie',slug:'sante',icon:'🏥'},
  educ:{id:'sec-07',name:'Éducation & Formation',slug:'education',icon:'🎓'},
  ener:{id:'sec-08',name:'Énergie & Environnement',slug:'energie',icon:'⚡'},
  btp:{id:'sec-09',name:'BTP & Immobilier',slug:'btp',icon:'🏗️'},
  comm:{id:'sec-10',name:'Commerce & Distribution',slug:'commerce',icon:'🛒'},
  tour:{id:'sec-11',name:'Tourisme & Hôtellerie',slug:'tourisme',icon:'🏨'},
  fin:{id:'sec-12',name:'Services Financiers',slug:'finance',icon:'🏦'},
} as const;
type E=[string,string,string,string,string,number,number,string,string[],boolean?];
function mk(e:E,i:number):AnnuaireEnterprise{
  const[n,sk,c,p,lf,y,em,d,t,digi]=e;const s=S[sk as keyof typeof S];
  const sl=n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);
  const x=String(i+1400).padStart(4,'0');
  return{id:`b5-${sl}`,rccm:`GA-LIB-${y}-E-${x}`,nif:`NIF-GA-${y}-${x}`,name:n,
    legalForm:lf as AnnuaireEnterprise['legalForm'],sector:s,status:'ACTIVE',
    address:{street:c,city:c,province:p,country:'Gabon'},
    description:d,employeeCount:em,yearFounded:y,isDigitalEcosystem:digi||false,
    tags:t,publicStats:{},createdAt:`${y}-01-01`,updatedAt:'2026-03-01'};
}
const D:E[]=[
  // ═══ INDUSTRIE AGROALIMENTAIRE ═══
  ['SOBRAGA - Brasseries du Gabon','agri','Libreville','Estuaire','SA',1966,800,'Brasserie nationale. Régab, Castel, eau Andza.',['brasserie','Régab','Castel']],
  ['BGI Gabon','agri','Libreville','Estuaire','SA',1968,300,'Brasserie Glacières Internationales.',['brasserie','boissons']],
  ['Coca-Cola Distribution Gabon','agri','Libreville','Estuaire','SA',1990,200,'Distribution Coca-Cola au Gabon.',['boissons','distribution']],
  ['Nestlé Gabon','agri','Libreville','Estuaire','SA',1995,100,'Produits alimentaires Nestlé.',['alimentaire','Nestlé']],
  ['Laiterie du Gabon','agri','Libreville','Estuaire','SA',2005,60,'Produits laitiers et yaourts.',['laitier','yaourts']],
  ['Boulangerie Industrielle du Gabon','agri','Libreville','Estuaire','SA',2000,80,'Pain et viennoiseries industriels.',['boulangerie','industriel']],
  ['Eaux Minérales Léconi','agri','Lékoni','Haut-Ogooué','SA',2008,40,'Production d\'eau minérale.',['eau','minérale']],
  ['SIAT Gabon','agri','Lambaréné','Moyen-Ogooué','SA',2004,700,'Huile de palme et caoutchouc.',['huile','palme','caoutchouc']],
  ['Olam Palm Gabon','agri','Mouila','Ngounié','SA',2010,600,'Plantations de palmier à huile.',['palmier','Olam']],
  ['Gabon Miel','agri','Libreville','Estuaire','SARL',2015,10,'Apiculture et miel gabonais.',['miel','apiculture']],
  ['Chocolaterie Gabonaise','agri','Libreville','Estuaire','SARL',2018,8,'Chocolat artisanal gabonais.',['chocolat','artisanal']],
  ['Conserverie du Gabon','agri','Libreville','Estuaire','SA',2000,50,'Conserves de thon et poisson.',['conserves','poisson']],
  // ═══ SERVICES INDUSTRIELS ═══
  ['Air Liquide Gabon','ener','Libreville','Estuaire','SA',1985,60,'Gaz industriels et médicaux.',['gaz','industriel']],
  ['SGS Gabon Inspection','comm','Libreville','Estuaire','SA',1990,40,'Inspection et certification.',['inspection']],
  ['Intertek Gabon','comm','Libreville','Estuaire','SA',2005,30,'Testing, inspection, certification.',['testing','certification']],
  ['Cotecna Gabon','comm','Libreville','Estuaire','SA',2008,25,'Vérification et conformité.',['vérification']],
  ['Bollore Africa Logistics','trans','Libreville','Estuaire','SA',1998,300,'Logistique intégrée.',['logistique','Bolloré']],
  // ═══ TÉLÉCOMMUNICATIONS ═══
  ['Fibre du Gabon','tech','Libreville','Estuaire','SA',2015,60,'Réseau fibre optique national.',['fibre','réseau'],true],
  ['ACE Submarine Cable Gabon','tech','Libreville','Estuaire','SA',2012,20,'Câble sous-marin international.',['câble','sous-marin'],true],
  ['SAT-3/WASC Gabon','tech','Libreville','Estuaire','SA',2002,15,'Câble sous-marin SAT-3.',['câble','international'],true],
  ['ANINF','tech','Libreville','Estuaire','SA',2011,80,'Agence nationale des infrastructures numériques.',['infrastructure','numérique','ANINF'],true],
  ['ARCEP Gabon','tech','Libreville','Estuaire','SA',2001,50,'Régulation des télécoms.',['régulation','télécoms'],true],
  ['Gabon TV','tech','Libreville','Estuaire','SA',1963,200,'Télévision nationale.',['TV','médias'],true],
  ['Radio Gabon','tech','Libreville','Estuaire','SA',1959,100,'Radio nationale.',['radio','médias'],true],
  ['RTG2','tech','Libreville','Estuaire','SA',2008,50,'2ème chaîne nationale.',['TV','chaîne'],true],
  ['L\'Union (journal)','tech','Libreville','Estuaire','SA',1975,80,'Quotidien national.',['presse','journal'],true],
  ['Gabon Review Media','tech','Libreville','Estuaire','SARL',2012,15,'Média en ligne.',['presse','digital'],true],
  // ═══ ASSOCIATIONS ET CHAMBRES ═══
  ['CCI Gabon - Chambre de Commerce','comm','Libreville','Estuaire','SA',1960,30,'Chambre de commerce et d\'industrie.',['CCI','commerce']],
  ['CGPME Gabon','comm','Libreville','Estuaire','SA',2005,10,'Confédération PME.',['PME','patronat']],
  ['Patronat Gabonais (CPG)','comm','Libreville','Estuaire','SA',1980,15,'Confédération patronale.',['patronat']],
  ['APIP Gabon','comm','Libreville','Estuaire','SA',2000,40,'Agence de promotion des investissements.',['investissement','promotion']],
  ['ONE Gabon','comm','Libreville','Estuaire','SA',2005,20,'Office national de l\'emploi.',['emploi','recrutement']],
  ['ANGTI','tech','Libreville','Estuaire','SA',2012,30,'Agence innovation et transfert.',['innovation','transfert'],true],
  // ═══ SERVICES FINANCIERS SUPPLÉMENTAIRES ═══
  ['Société Financière Gabonaise (SFG)','fin','Libreville','Estuaire','SA',2005,25,'Société de financement.',['financement']],
  ['Crédit Foncier du Gabon','fin','Libreville','Estuaire','SA',1990,50,'Crédit immobilier.',['crédit','immobilier']],
  ['Société de Gestion d\'Actifs','fin','Libreville','Estuaire','SA',2010,15,'Gestion de portefeuilles.',['gestion','actifs']],
  ['Gabon Capital Investments','fin','Libreville','Estuaire','SA',2015,10,'Capital investissement.',['capital','investissement']],
  ['Fonds Gabonais d\'Investissement','fin','Libreville','Estuaire','SA',2012,20,'Fonds souverain.',['fonds','souverain']],
  // ═══ BTP — Matériaux et services ═══
  ['Groupe Asonga','btp','Libreville','Estuaire','SA',2005,100,'Construction et promotion immobilière.',['construction','promotion']],
  ['Gabon Béton Prêt','btp','Libreville','Estuaire','SARL',2010,30,'Béton prêt à l\'emploi.',['béton']],
  ['Charpentes Métalliques Gabon','btp','Libreville','Estuaire','SA',2005,40,'Charpentes et structures métalliques.',['charpente','métallique']],
  ['Fondations Profondes Gabon','btp','Libreville','Estuaire','SA',2008,25,'Fondations et pieux.',['fondations']],
  ['Gabon Clim Services','btp','Libreville','Estuaire','SARL',2012,15,'Climatisation professionnelle.',['climatisation']],
  ['Toiture du Gabon','btp','Libreville','Estuaire','SARL',2010,12,'Toitures et couvertures.',['toiture']],
  ['Piscines et Loisirs Gabon','btp','Libreville','Estuaire','SARL',2015,8,'Construction de piscines.',['piscines']],
  // ═══ COMMERCE — Import-Export ═══
  ['SOCIGA','comm','Libreville','Estuaire','SA',1975,100,'Import-export produits industriels.',['import','industriel']],
  ['ETS Mounanga','comm','Libreville','Estuaire','SARL',1990,30,'Commerce général et import.',['commerce','import']],
  ['Groupe Ping','comm','Libreville','Estuaire','SA',2000,80,'Import et distribution.',['import','distribution']],
  ['Global Business Gabon','comm','Libreville','Estuaire','SARL',2010,15,'Commerce international.',['commerce','international']],
  ['ETS Biyoghe','comm','Libreville','Estuaire','SARL',2005,20,'Commerce et négoce.',['commerce','négoce']],
  ['Gabon Cosmétiques','comm','Libreville','Estuaire','SARL',2012,10,'Cosmétiques et beauté.',['cosmétiques','beauté']],
  ['Agro Import Gabon','comm','Libreville','Estuaire','SARL',2008,12,'Import de produits agricoles.',['import','agricole']],
  ['Matériaux Express','comm','Libreville','Estuaire','SARL',2015,8,'Distribution matériaux.',['matériaux']],
  // ═══ TRANSPORT supplémentaire ═══
  ['Setrag - Transgabonais','trans','Libreville','Estuaire','SA',1978,1200,'Chemin de fer Transgabonais.',['rail','train']],
  ['ADL - Aéroport de Libreville','trans','Libreville','Estuaire','SA',2000,300,'Gestion aéroport Léon Mba.',['aéroport']],
  ['Afrijet Business Services','trans','Libreville','Estuaire','SA',2005,150,'Compagnie aérienne régionale.',['aérien','Afrijet']],
  ['Fly Gabon','trans','Libreville','Estuaire','SA',2022,50,'Nouvelle compagnie nationale.',['aérien','national']],
  ['SONATRAM','trans','Libreville','Estuaire','SA',1990,200,'Transport routier national.',['routier','national']],
  // ═══ MINES — Services pétroliers ═══
  ['Perenco Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1993,250,'Producteur pétrolier majeur.',['pétrole','production']],
  ['CNR International Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2005,60,'Exploration pétrolière.',['exploration']],
  ['Harvest Natural Resources','mines','Port-Gentil','Ogooué-Maritime','SA',2008,40,'Concessions pétrolières.',['concessions']],
  ['MPDC Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2010,50,'Murphy Petroleum Development.',['Murphy','pétrole']],
  ['Assala Energy','mines','Port-Gentil','Ogooué-Maritime','SA',2017,200,'Opérateur pétrolier indépendant.',['pétrole','indépendant']],
  // ═══ BOIS — Transformation GSEZ ═══
  ['Precious Woods Gabon (CEB)','bois','Libreville','Estuaire','SA',1998,350,'Exploitation certifiée FSC.',['FSC','certifié']],
  ['TGI - Tropical Gabon Industries','bois','Nkok','Estuaire','SA',2014,100,'Contreplaqué et placage.',['contreplaqué','GSEZ']],
  ['BSG - Bois Spéciaux du Gabon','bois','Libreville','Estuaire','SA',2005,60,'Bois précieux et spéciaux.',['bois précieux']],
  ['Gabonese Timber Marketing','bois','Libreville','Estuaire','SA',2008,30,'Marketing et négoce de bois.',['négoce','marketing']],
  ['CNPB Gabon','bois','Libreville','Estuaire','SA',2010,25,'Centre national du bois.',['centre','promotion']],
  // ═══ ÉNERGIE supplémentaire ═══
  ['SEG - Société d\'Énergie du Gabon','ener','Libreville','Estuaire','SA',2020,100,'Nouvelle société d\'énergie.',['énergie','distribution']],
  ['Barrage de Grand Poubara','ener','Franceville','Haut-Ogooué','SA',2013,60,'Centrale hydroélectrique.',['hydroélectrique','barrage']],
  ['Barrage du Kinguélé','ener','Libreville','Estuaire','SA',1980,40,'Centrale hydro historique.',['hydroélectrique']],
  ['FDE - Fonds de Développement Énergétique','ener','Libreville','Estuaire','SA',2010,20,'Financement projets énergétiques.',['financement','énergie']],
  // ═══ SANTÉ supplémentaire ═══
  ['Institut de Cancérologie de Libreville','sante','Libreville','Estuaire','SA',2015,40,'Traitement des cancers.',['cancérologie']],
  ['Centre de Dialyse du Gabon','sante','Libreville','Estuaire','SA',2010,25,'Dialyse rénale.',['dialyse','rénal']],
  ['Clinique du Sommeil','sante','Libreville','Estuaire','SARL',2018,8,'Troubles du sommeil.',['sommeil']],
  ['Centre d\'Ophtalmologie','sante','Libreville','Estuaire','SARL',2012,12,'Ophtalmologie et chirurgie des yeux.',['ophtalmologie']],
  ['Kinésithérapie du Gabon','sante','Libreville','Estuaire','SARL',2008,6,'Rééducation et kinésithérapie.',['kinésithérapie']],
  ['Centre de Cardiologie','sante','Libreville','Estuaire','SARL',2015,10,'Cardiologie et suivi cardiaque.',['cardiologie']],
  // ═══ TOURISME supplémentaire ═══
  ['Corisco Island Lodge','tour','Corisco','Estuaire','SARL',2015,8,'Lodge île Corisco.',['île','lodge']],
  ['Cap Esterias Beach Club','tour','Libreville','Estuaire','SARL',2010,15,'Club de plage.',['plage','club']],
  ['Golf Présidentiel de Libreville','tour','Libreville','Estuaire','SA',1980,20,'Parcours de golf 18 trous.',['golf']],
  ['Casino Croisette Libreville','tour','Libreville','Estuaire','SA',2005,40,'Casino et divertissement.',['casino','divertissement']],
  ['Bowling Libreville','tour','Libreville','Estuaire','SARL',2010,10,'Bowling et loisirs.',['bowling','loisirs']],
  ['Parc Aquatique de Libreville','tour','Libreville','Estuaire','SARL',2015,15,'Parc aquatique familial.',['parc','aquatique']],
  ['Centre Culturel Français','tour','Libreville','Estuaire','SA',1960,30,'Culture, spectacles, expositions.',['culture','spectacles']],
  // ═══ ÉDUCATION supplémentaire ═══
  ['INSG - Institut National des Sciences de Gestion','educ','Libreville','Estuaire','SA',1970,40,'Formation en gestion.',['gestion','management']],
  ['École des Mines et Métallurgie de Moanda','educ','Moanda','Haut-Ogooué','SA',2005,30,'Formation minière.',['mines','formation']],
  ['Centre Universitaire de Franceville','educ','Franceville','Haut-Ogooué','SA',2012,60,'Centre universitaire régional.',['université']],
  ['EPAM - École Préparatoire aux Arts et Métiers','educ','Libreville','Estuaire','SA',1990,25,'Préparation arts et métiers.',['artisanat','prépa']],
  ['Informatique Gabon Formation','educ','Libreville','Estuaire','SARL',2010,10,'Formation continue en informatique.',['informatique','formation']],
  // ═══ COMMERCE supplémentaire ═══
  ['Gabon Distribution (GDS)','comm','Libreville','Estuaire','SA',2005,60,'Distribution en gros.',['distribution','gros']],
  ['ETS Ndong','comm','Libreville','Estuaire','SARL',2000,15,'Commerce et quincaillerie.',['commerce']],
  ['Mini Prix Gabon','comm','Libreville','Estuaire','SARL',2012,20,'Supermarché discount.',['supermarché','discount']],
  ['Espace Bijoux Gabon','comm','Libreville','Estuaire','EI',2015,4,'Bijouterie fantaisie.',['bijouterie']],
  ['Décoration Intérieure Gabon','comm','Libreville','Estuaire','SARL',2010,8,'Design d\'intérieur.',['décoration','design']],
  ['Promo Cash Gabon','comm','Libreville','Estuaire','SA',2005,40,'Cash and carry, distribution.',['cash carry']],
  ['Galeries du Gabon','comm','Libreville','Estuaire','SA',2008,30,'Centre commercial.',['centre commercial']],
  // ═══ SERVICES DIVERS ═══
  ['Agence ONEP','comm','Libreville','Estuaire','SA',2000,25,'Agence nationale de l\'eau potable.',['eau','ONEP']],
  ['Poste Gabon (Gabon Poste)','comm','Libreville','Estuaire','SA',1960,500,'Services postaux nationaux.',['poste','courrier']],
  ['Gabon Broadcasting System','tech','Libreville','Estuaire','SA',2010,30,'Diffusion audiovisuelle.',['diffusion','audiovisuel'],true],
  ['IGCS - Institut Gabonais du Cloud','tech','Libreville','Estuaire','SARL',2021,8,'Cloud souverain gabonais.',['cloud','souverain'],true],
  ['Blockchain Gabon','tech','Libreville','Estuaire','SARL',2022,5,'Solutions blockchain.',['blockchain'],true],
  ['AI Gabon Labs','tech','Libreville','Estuaire','SARL',2023,4,'Intelligence artificielle.',['IA','AI'],true],
  ['IoT Solutions Gabon','tech','Libreville','Estuaire','SARL',2020,6,'Internet des objets.',['IoT','objets connectés'],true],
  ['Drone Gabon Services','tech','Libreville','Estuaire','SARL',2019,8,'Services de drones.',['drones','aérien'],true],
  ['3D Print Gabon','tech','Libreville','Estuaire','SARL',2021,4,'Impression 3D.',['impression 3D'],true],
  ['GreenTech Gabon','tech','Libreville','Estuaire','SARL',2020,6,'Technologies vertes.',['green','cleantech'],true],
  // ═══ DERNIERS AJOUTS POUR 1000+ ═══
  ['Multipress Gabon','comm','Libreville','Estuaire','SA',1988,45,'Imprimerie offset et numérique.',['imprimerie']],
  ['Gabon Presse Édition','comm','Libreville','Estuaire','SARL',2005,12,'Édition et publication.',['édition']],
  ['Cabinet Notarial Ndong','comm','Libreville','Estuaire','EI',2000,6,'Notaire.',['notaire']],
  ['Cabinet Notarial Obame','comm','Libreville','Estuaire','EI',2005,5,'Notaire.',['notaire']],
  ['Huissier de Justice Essono','comm','Libreville','Estuaire','EI',2008,4,'Huissier de justice.',['huissier']],
  ['Cabinet Avocat Nze','comm','Libreville','Estuaire','EI',2005,6,'Avocat d\'affaires.',['avocat']],
  ['Cabinet Avocat Mintsa','comm','Libreville','Estuaire','EI',2010,5,'Droit des sociétés et OHADA.',['avocat','OHADA']],
  ['Assurances Générales du Gabon','fin','Libreville','Estuaire','SA',2005,50,'Assurance multibranche.',['assurance']],
  ['Banque Atlantique Gabon','fin','Libreville','Estuaire','SA',2010,80,'Banque du groupe Atlantique.',['banque']],
  ['BGFI Bourse','fin','Libreville','Estuaire','SA',2008,15,'Intermédiation boursière BVMAC.',['bourse','BVMAC']],
  ['Gabon Reinsurance','fin','Libreville','Estuaire','SA',2015,20,'Réassurance locale.',['réassurance']],
  ['immobilière Loukas','btp','Libreville','Estuaire','SARL',2010,8,'Promotion et vente immobilière.',['immobilier']],
  ['Résidence du Bord de Mer','btp','Libreville','Estuaire','SARL',2015,5,'Résidences de standing.',['résidence']],
  ['Laverie Express Gabon','comm','Libreville','Estuaire','SARL',2018,6,'Laverie automatique.',['laverie']],
  ['Traiteur Royal Gabon','tour','Libreville','Estuaire','SARL',2012,10,'Traiteur événementiel.',['traiteur']],
];
export const BATCH5_ENTERPRISES:AnnuaireEnterprise[]=D.map((e,i)=>mk(e,i));
