import type { AnnuaireEnterprise } from './annuaire-data';
const S={
  tech:{id:'sec-01',name:"Technologies de l'Information",slug:'technologies',icon:'💻'},
  agri:{id:'sec-02',name:'Agriculture & Agroalimentaire',slug:'agriculture',icon:'🌾'},
  mines:{id:'sec-03',name:'Mines & Hydrocarbures',slug:'mines',icon:'⛏️'},
  trans:{id:'sec-04',name:'Transport & Logistique',slug:'transport',icon:'🚛'},
  bois:{id:'sec-05',name:'Bois & Forêt',slug:'bois',icon:'🌳'},
  sante:{id:'sec-06',name:'Santé & Pharmacie',slug:'sante',icon:'🏥'},
  educ:{id:'sec-07',name:'Éducation & Formation',slug:'education',icon:'🎓'},
  ener:{id:'sec-08',name:'Énergie & Environnement',slug:'energie',icon:'⚡'},
  btp:{id:'sec-09',name:'BTP & Immobilier',slug:'btp',icon:'🏗️'},
  comm:{id:'sec-10',name:'Commerce & Distribution',slug:'commerce',icon:'🛒'},
  tour:{id:'sec-11',name:'Tourisme & Hôtellerie',slug:'tourisme',icon:'🏨'},
  fin:{id:'sec-12',name:'Services Financiers',slug:'finance',icon:'🏦'},
} as const;
type E=[string,string,string,string,string,number,number,string,string[],boolean?];
function mk(e:E,i:number):AnnuaireEnterprise{
  const[n,sk,c,p,lf,y,em,d,t,digi]=e;const s=S[sk as keyof typeof S];
  const sl=n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);
  const x=String(i+800).padStart(4,'0');
  return{id:`b3-${sl}`,rccm:`GA-LIB-${y}-C-${x}`,nif:`NIF-GA-${y}-${x}`,name:n,
    legalForm:lf as AnnuaireEnterprise['legalForm'],sector:s,status:'ACTIVE',
    address:{street:c,city:c,province:p,country:'Gabon'},
    description:d,employeeCount:em,yearFounded:y,isDigitalEcosystem:digi||false,
    tags:t,publicStats:{},createdAt:`${y}-01-01`,updatedAt:'2026-03-01'};
}
const D:E[]=[
  // ═══ PORT-GENTIL (2ème ville, capitale économique pétrolière) ═══
  ['Hôtel Mandji','tour','Port-Gentil','Ogooué-Maritime','SA',1985,40,'Hôtel historique de Port-Gentil.',['hôtel']],
  ['Restaurant Cap Lopez','tour','Port-Gentil','Ogooué-Maritime','SARL',2010,12,'Restaurant fruits de mer Cap Lopez.',['restaurant']],
  ['Clinique du Littoral','sante','Port-Gentil','Ogooué-Maritime','SARL',2005,35,'Clinique privée Port-Gentil.',['clinique']],
  ['Cabinet Médical Ntchengue','sante','Port-Gentil','Ogooué-Maritime','EI',2008,8,'Cabinet médecine générale.',['cabinet']],
  ['Pharmacie du Port','sante','Port-Gentil','Ogooué-Maritime','EI',2000,7,'Pharmacie centre Port-Gentil.',['pharmacie']],
  ['Pharmacie de la Balise','sante','Port-Gentil','Ogooué-Maritime','EI',2004,6,'Pharmacie quartier Balise.',['pharmacie']],
  ['Pharmacie Saint-Hilaire','sante','Port-Gentil','Ogooué-Maritime','EI',2006,6,'Parapharmacie et pharmacie.',['pharmacie']],
  ['Supermarché Marina','comm','Port-Gentil','Ogooué-Maritime','SARL',2010,20,'Supermarché Marina.',['supermarché']],
  ['Quincaillerie Marine','comm','Port-Gentil','Ogooué-Maritime','SARL',2005,10,'Fournitures marines et quincaillerie.',['marine','quincaillerie']],
  ['Garage Auto Service PG','comm','Port-Gentil','Ogooué-Maritime','SARL',2012,12,'Garage et mécanique auto.',['garage','auto']],
  ['Total Marketing PG','comm','Port-Gentil','Ogooué-Maritime','SA',2000,30,'Station service et lubrifiants.',['carburant','station']],
  ['Sogara Services','mines','Port-Gentil','Ogooué-Maritime','SA',1998,150,'Services associés à la raffinerie.',['raffinerie','services']],
  ['ENTP Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2005,120,'Entreprise nationale de travaux pétroliers.',['forage','pétrolier']],
  ['Saipem Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2000,200,'Ingénierie et construction pétrolière.',['ingénierie','pétrole']],
  ['Technip Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',1995,180,'Ingénierie sous-marine et offshore.',['offshore','ingénierie']],
  ['Smith International Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2002,80,'Outils de forage et technologies.',['forage','outils']],
  ['Subsea 7 Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2008,100,'Ingénierie sous-marine.',['sous-marine','subsea']],
  ['AESP - Agence pour la Sécurité Pétrolière','mines','Port-Gentil','Ogooué-Maritime','SA',2010,40,'Sécurité des opérations pétrolières.',['sécurité','pétrole']],
  ['SOCAPE - Sté de Catering Pétrolier','tour','Port-Gentil','Ogooué-Maritime','SA',2005,80,'Catering pour plateformes offshore.',['catering','offshore']],
  ['Trans Ocean Gabon','mines','Port-Gentil','Ogooué-Maritime','SA',2006,60,'Forage offshore ultra-profond.',['forage','offshore']],
  ['Port-Gentil Auto Parts','comm','Port-Gentil','Ogooué-Maritime','SARL',2010,10,'Pièces détachées automobiles.',['auto','pièces']],
  ['BTP du Littoral','btp','Port-Gentil','Ogooué-Maritime','SARL',2008,40,'Construction et rénovation.',['construction']],
  ['Agence Maritime du Gabon','trans','Port-Gentil','Ogooué-Maritime','SA',1985,50,'Agence maritime et consignation.',['maritime','consignation']],
  // ═══ FRANCEVILLE & HAUT-OGOOUÉ ═══
  ['Hôtel La Résidence Franceville','tour','Franceville','Haut-Ogooué','SARL',2005,25,'Hôtel de charme à Franceville.',['hôtel']],
  ['Restaurant Le Masuku','tour','Franceville','Haut-Ogooué','EI',2010,8,'Restaurant local à Franceville.',['restaurant']],
  ['Clinique de Franceville','sante','Franceville','Haut-Ogooué','SARL',2000,30,'Clinique privée multispécialités.',['clinique']],
  ['Pharmacie de Masuku','sante','Franceville','Haut-Ogooué','EI',2005,6,'Pharmacie de Franceville.',['pharmacie']],
  ['Supermarché Franceville Centre','comm','Franceville','Haut-Ogooué','SARL',2008,15,'Alimentation générale.',['supermarché']],
  ['BTP Haut-Ogooué','btp','Franceville','Haut-Ogooué','SARL',2005,50,'Construction et génie civil.',['construction']],
  ['Transport Franceville Express','trans','Franceville','Haut-Ogooué','SARL',2012,15,'Transport de personnes.',['transport']],
  ['Banque Franceville BGFI','fin','Franceville','Haut-Ogooué','SA',2002,30,'Agence BGFI Franceville.',['banque','agence']],
  ['École Bilingue de Franceville','educ','Franceville','Haut-Ogooué','SARL',2010,15,'École bilingue privée.',['école','bilingue']],
  ['Menuiserie du Haut-Ogooué','bois','Franceville','Haut-Ogooué','EI',2008,8,'Menuiserie et ébénisterie.',['menuiserie']],
  // ═══ OYEM & WOLEU-NTEM ═══
  ['Hôtel Mont Fébé Oyem','tour','Oyem','Woleu-Ntem','SARL',2010,20,'Hôtel principal d\'Oyem.',['hôtel']],
  ['Restaurant Le Ntem','tour','Oyem','Woleu-Ntem','EI',2012,6,'Restaurant cuisine locale.',['restaurant']],
  ['Clinique d\'Oyem','sante','Oyem','Woleu-Ntem','SARL',2005,25,'Clinique privée d\'Oyem.',['clinique']],
  ['Commerce Général Oyem','comm','Oyem','Woleu-Ntem','SARL',2008,10,'Commerce généraliste.',['commerce']],
  ['Cacao Woleu-Ntem','agri','Oyem','Woleu-Ntem','SARL',2010,20,'Production et export de cacao.',['cacao']],
  ['Transport du Nord','trans','Oyem','Woleu-Ntem','SARL',2012,12,'Transport routier Nord.',['transport']],
  ['Scierie du Ntem','bois','Oyem','Woleu-Ntem','SARL',2009,30,'Scierie locale.',['scierie']],
  ['Bitam Agri-Business','agri','Bitam','Woleu-Ntem','SARL',2015,15,'Agriculture et élevage.',['agriculture']],
  ['BTP Nord Gabon','btp','Oyem','Woleu-Ntem','SARL',2010,25,'Construction dans le Nord.',['construction']],
  // ═══ LAMBARÉNÉ & MOYEN-OGOOUÉ ═══
  ['Hôtel Schweitzer','tour','Lambaréné','Moyen-Ogooué','SARL',2005,20,'Hôtel historique Lambaréné.',['hôtel','Schweitzer']],
  ['Restaurant de l\'Ogooué','tour','Lambaréné','Moyen-Ogooué','EI',2008,8,'Restaurant au bord de l\'Ogooué.',['restaurant']],
  ['Transport Fluvial de l\'Ogooué','trans','Lambaréné','Moyen-Ogooué','SARL',2005,20,'Transport fluvial passagers et marchandises.',['fluvial']],
  ['Pêcheries du Moyen-Ogooué','agri','Lambaréné','Moyen-Ogooué','SARL',2010,15,'Pêche artisanale et vente.',['pêche']],
  ['Hévéaculture de Lambaréné','agri','Lambaréné','Moyen-Ogooué','SA',2005,100,'Exploitation d\'hévéa.',['hévéa']],
  ['Clinique Schweitzer','sante','Lambaréné','Moyen-Ogooué','SA',1913,80,'Hôpital historique Albert Schweitzer.',['hôpital','historique']],
  // ═══ MOUILA & NGOUNIÉ ═══
  ['Hôtel de la Ngounié','tour','Mouila','Ngounié','SARL',2008,15,'Hôtel de Mouila.',['hôtel']],
  ['Grande Pharmacie de Mouila','sante','Mouila','Ngounié','EI',2006,5,'Pharmacie de Mouila.',['pharmacie']],
  ['Café et Cacao Ngounié','agri','Mouila','Ngounié','SARL',2012,25,'Production café et cacao.',['café','cacao']],
  ['BTP Ngounié','btp','Mouila','Ngounié','SARL',2010,20,'Construction Ngounié.',['construction']],
  ['Transport Mouila Express','trans','Mouila','Ngounié','SARL',2015,10,'Transport de personnes.',['transport']],
  // ═══ TCHIBANGA & NYANGA ═══
  ['Hôtel du Mayumba','tour','Tchibanga','Nyanga','SARL',2010,12,'Hôtel de Tchibanga.',['hôtel']],
  ['Pharmacie de Tchibanga Centre','sante','Tchibanga','Nyanga','EI',2008,4,'Pharmacie centre Tchibanga.',['pharmacie']],
  ['Pêche Nyanga','agri','Tchibanga','Nyanga','SARL',2012,10,'Pêche maritime et artisanale.',['pêche']],
  ['Mayumba Eco-Lodge','tour','Mayumba','Nyanga','SARL',2015,8,'Écolodge tortues marines.',['écolodge','écotourisme']],
  // ═══ MAKOKOU & OGOOUÉ-IVINDO ═══
  ['Hôtel Belinga','tour','Makokou','Ogooué-Ivindo','SARL',2010,12,'Hôtel de Makokou.',['hôtel']],
  ['Pharmacie de Makokou Centre','sante','Makokou','Ogooué-Ivindo','EI',2009,4,'Pharmacie de Makokou.',['pharmacie']],
  ['Ivindo Tourisme','tour','Makokou','Ogooué-Ivindo','SARL',2015,10,'Écotourisme chutes de Kongou.',['écotourisme','Kongou']],
  ['Exploitation Forestière Ivindo','bois','Makokou','Ogooué-Ivindo','SA',2005,60,'Exploitation forestière Ivindo.',['exploitation']],
  // ═══ KOULAMOUTOU & OGOOUÉ-LOLO ═══
  ['Hôtel de Koulamoutou','tour','Koulamoutou','Ogooué-Lolo','SARL',2008,10,'Hôtel de Koulamoutou.',['hôtel']],
  ['Pharmacie de Koulamoutou','sante','Koulamoutou','Ogooué-Lolo','EI',2007,4,'Pharmacie de Koulamoutou.',['pharmacie']],
  ['Transport Lolo Express','trans','Koulamoutou','Ogooué-Lolo','SARL',2012,8,'Transport inter-urbain.',['transport']],
  // ═══ LIBREVILLE — SUPPLÉMENTAIRES TOUTES CATÉGORIES ═══
  // Restaurants & Food
  ['Restaurant La Paillote','tour','Libreville','Estuaire','SARL',2005,15,'Restaurant terrasse bord de mer.',['restaurant']],
  ['Restaurant Iguane Café','tour','Libreville','Estuaire','SARL',2010,12,'Bar restaurant ambiance tropicale.',['restaurant','bar']],
  ['Restaurant Le Loft','tour','Libreville','Estuaire','SARL',2015,10,'Restaurant tendance, cuisine fusion.',['restaurant','fusion']],
  ['Restaurant Le N\'Koltang','tour','Libreville','Estuaire','SARL',2012,8,'Restaurant gabonais traditionnel.',['restaurant','traditionnel']],
  ['Pizzeria Napoli Libreville','tour','Libreville','Estuaire','EI',2014,8,'Pizzeria artisanale italienne.',['pizzeria']],
  ['Restaurant L\'Alizé','tour','Libreville','Estuaire','SARL',2008,12,'Restaurant français gastronomique.',['restaurant','français']],
  ['Fast Food Chicken House','tour','Libreville','Estuaire','EI',2018,10,'Restauration rapide poulet.',['fast food']],
  ['Restaurant Le Baobab','tour','Libreville','Estuaire','SARL',2016,8,'Restaurant buffet africain.',['restaurant','africain']],
  ['Glacier du Bord de Mer','tour','Libreville','Estuaire','EI',2015,5,'Glaces artisanales.',['glacier']],
  ['Boulangerie du Plateau','tour','Libreville','Estuaire','EI',2010,8,'Boulangerie pâtisserie.',['boulangerie']],
  // Pharmacies supplémentaires Libreville
  ['Pharmacie Atong-Abé','sante','Libreville','Estuaire','EI',2008,7,'Pharmacie Atong-Abé.',['pharmacie']],
  ['Pharmacie Belle-Vue','sante','Libreville','Estuaire','EI',2010,6,'Pharmacie Belle-Vue.',['pharmacie']],
  ['Pharmacie Sotega','sante','Libreville','Estuaire','EI',2005,7,'Pharmacie zone Sotega.',['pharmacie']],
  ['Pharmacie de la Cité','sante','Libreville','Estuaire','EI',2003,8,'Pharmacie quartier résidentiel.',['pharmacie']],
  ['Pharmacie IAI','sante','Libreville','Estuaire','EI',2006,6,'Pharmacie quartier IAI.',['pharmacie']],
  ['Parapharmacie Santé Plus','sante','Libreville','Estuaire','SARL',2015,5,'Parapharmacie et compléments.',['parapharmacie']],
  ['Optique du Gabon','sante','Libreville','Estuaire','SARL',2010,8,'Opticien lunetterie.',['optique','lunettes']],
  ['Laboratoire Bio-Analyses','sante','Libreville','Estuaire','SARL',2005,20,'Laboratoire d\'analyses médicales.',['laboratoire','analyses']],
  // Commerce Libreville
  ['Brico Gabon','comm','Libreville','Estuaire','SARL',2012,25,'Bricolage et outillage.',['bricolage','outillage']],
  ['Centrale d\'Achat du Gabon','comm','Libreville','Estuaire','SA',2005,50,'Achat groupé pour entreprises.',['achat','grossiste']],
  ['Magasin Tech Store','comm','Libreville','Estuaire','SARL',2018,8,'Informatique et high-tech.',['informatique','tech']],
  ['Auto Center Gabon','comm','Libreville','Estuaire','SARL',2010,15,'Entretien et réparation automobile.',['auto','entretien']],
  ['Station Total Lalala','comm','Libreville','Estuaire','SA',2000,10,'Station service carburant.',['carburant','station']],
  ['Station Shell Oloumi','comm','Libreville','Estuaire','SA',2002,10,'Station service Shell.',['carburant','station']],
  ['Librairie Raponda Walker','comm','Libreville','Estuaire','SARL',2005,8,'Librairie spécialisée Gabon.',['librairie']],
  ['Pneu Service Gabon','comm','Libreville','Estuaire','SARL',2008,10,'Pneumatiques et alignement.',['pneu','auto']],
  ['Espace Meuble Gabon','comm','Libreville','Estuaire','SARL',2010,12,'Ameublement et décoration.',['meuble','décoration']],
  ['Matériaux de Construction Gabon (MCG)','comm','Libreville','Estuaire','SA',2005,40,'Distribution matériaux BTP.',['matériaux','BTP']],
  ['Jardinerie Tropicale','comm','Libreville','Estuaire','SARL',2015,6,'Plantes et jardinage tropical.',['jardinerie']],
  ['Animalerie du Gabon','comm','Libreville','Estuaire','EI',2018,4,'Accessoires et soins animaux.',['animalerie']],
  // BTP Libreville
  ['Peinture Gabon (PEIGA)','btp','Libreville','Estuaire','SARL',2005,30,'Peinture bâtiment et décoration.',['peinture','décoration']],
  ['Electricité Gabon Services','btp','Libreville','Estuaire','SARL',2008,25,'Installation électrique.',['électricité','installation']],
  ['Plomberie Moderne Gabon','btp','Libreville','Estuaire','SARL',2010,15,'Plomberie et sanitaire.',['plomberie']],
  ['Climatisation Gabon (CLIMGAB)','btp','Libreville','Estuaire','SARL',2005,20,'Installation climatisation.',['climatisation','HVAC']],
  ['Ascenseurs du Gabon','btp','Libreville','Estuaire','SARL',2012,10,'Installation et maintenance ascenseurs.',['ascenseurs']],
  ['Géomètre Expert Gabon','btp','Libreville','Estuaire','EI',2008,5,'Topographie et bornage.',['géomètre','topographie']],
  ['Architecture et Design Gabon','btp','Libreville','Estuaire','SARL',2010,8,'Cabinet d\'architecture.',['architecture','design']],
  ['Carrelage et Sols Gabon','btp','Libreville','Estuaire','SARL',2012,12,'Pose de carrelage et revêtements.',['carrelage']],
  ['Étanchéité Gabon','btp','Libreville','Estuaire','SARL',2015,10,'Étanchéité toiture et terrasse.',['étanchéité']],
  ['Vitrerie du Gabon','btp','Libreville','Estuaire','SARL',2010,8,'Miroiterie et vitrerie.',['vitrerie']],
  // Transport Libreville
  ['Taxi Vert Libreville','trans','Libreville','Estuaire','SARL',2018,20,'Service de taxi moderne.',['taxi']],
  ['Déménagement National Gabon','trans','Libreville','Estuaire','SARL',2010,15,'Déménagement national et international.',['déménagement']],
  ['Coursier Express LBV','trans','Libreville','Estuaire','SARL',2016,12,'Livraison rapide à Libreville.',['livraison','coursier']],
  ['Location 4x4 Gabon','trans','Libreville','Estuaire','SARL',2012,10,'Location de 4x4 et véhicules tout-terrain.',['location','4x4']],
  ['Hertz Gabon','trans','Libreville','Estuaire','SA',2005,25,'Location de véhicules Hertz.',['location','Hertz']],
  ['Europcar Gabon','trans','Libreville','Estuaire','SA',2008,20,'Location auto Europcar.',['location','Europcar']],
  // Services & Tech
  ['Gabon Web Agency','tech','Libreville','Estuaire','SARL',2015,8,'Création de sites web et SEO.',['web','SEO'],true],
  ['Digital Marketing Gabon','tech','Libreville','Estuaire','SARL',2018,6,'Marketing digital et publicité en ligne.',['marketing','digital'],true],
  ['Gabon Mobile Apps','tech','Libreville','Estuaire','SARL',2019,5,'Développement applications mobiles.',['mobile','apps'],true],
  ['Print & Copy Center','comm','Libreville','Estuaire','SARL',2010,10,'Impression et reprographie.',['impression','copie']],
  ['Studio Photo Gabon','comm','Libreville','Estuaire','EI',2012,4,'Photographie studio et événementiel.',['photo','studio']],
  ['Gabon Wedding Planner','comm','Libreville','Estuaire','EI',2016,3,'Organisation de mariages.',['mariage','événementiel']],
  ['Fitness Club Gabon','tour','Libreville','Estuaire','SARL',2015,10,'Salle de sport et fitness.',['fitness','sport']],
  ['Yoga Studio Libreville','tour','Libreville','Estuaire','EI',2018,4,'Yoga et bien-être.',['yoga','bien-être']],
  ['Auto-École Moderne','educ','Libreville','Estuaire','SARL',2005,12,'Formation à la conduite.',['auto-école']],
  ['Centre de Langues Gabon','educ','Libreville','Estuaire','SARL',2010,8,'Cours de langues étrangères.',['langues']],
  ['Crèche Les Petits Gabonais','educ','Libreville','Estuaire','SARL',2012,15,'Crèche et garderie.',['crèche','petite enfance']],
  ['Garderie Arc-en-Ciel','educ','Libreville','Estuaire','SARL',2015,10,'Garde d\'enfants.',['garderie']],
  // Agriculture supplémentaire
  ['SOGAPAL - Sté Gabonaise de Palmier','agri','Libreville','Estuaire','SA',2005,150,'Exploitation de palmier à huile.',['palmier','huile']],
  ['Élevage du Gabon','agri','Libreville','Estuaire','SARL',2010,30,'Élevage volaille et bétail.',['élevage']],
  ['Gabon Fruits','agri','Libreville','Estuaire','SARL',2015,20,'Production et export de fruits.',['fruits','export']],
  ['Igname du Gabon','agri','Oyem','Woleu-Ntem','SARL',2012,10,'Culture et vente d\'ignames.',['igname']],
  ['Manioc Express','agri','Libreville','Estuaire','SARL',2016,8,'Transformation du manioc.',['manioc','transformation']],
  ['Bananeraie du Woleu','agri','Oyem','Woleu-Ntem','SARL',2014,15,'Plantation de bananes.',['banane']],
  // Énergie supplémentaire
  ['Station-Service Pétro Gabon','ener','Libreville','Estuaire','SA',2008,30,'Réseau de stations-service.',['station-service']],
  ['GreenPower Gabon','ener','Libreville','Estuaire','SARL',2020,10,'Énergie solaire résidentielle.',['solaire']],
  ['Gabon Eau Solutions','ener','Libreville','Estuaire','SARL',2015,15,'Traitement et distribution d\'eau.',['eau','traitement']],
  ['Biogaz Gabon','ener','Libreville','Estuaire','SARL',2019,8,'Production de biogaz.',['biogaz','renouvelable']],
  // Finances supplémentaires
  ['Change Express Gabon','fin','Libreville','Estuaire','SARL',2010,5,'Bureau de change.',['change','devise']],
  ['Assurance Vie du Gabon','fin','Libreville','Estuaire','SA',2005,40,'Assurance vie et épargne.',['assurance','vie']],
  ['Cabinet Fiduciaire de l\'Estuaire','fin','Libreville','Estuaire','SARL',2008,10,'Comptabilité et gestion.',['comptabilité']],
  ['Gabon Leasing','fin','Libreville','Estuaire','SA',2010,20,'Crédit-bail et leasing.',['leasing','crédit-bail']],
  ['Express Transfert Gabon','fin','Libreville','Estuaire','SARL',2015,8,'Transferts d\'argent rapides.',['transferts']],
  // Bois supplémentaires
  ['Menuiserie Industrielle du Gabon','bois','Libreville','Estuaire','SA',2005,40,'Menuiserie industrielle.',['menuiserie','industrielle']],
  ['Ébénisterie d\'Art Gabon','bois','Libreville','Estuaire','EI',2010,6,'Ébénisterie d\'art et meubles.',['ébénisterie','art']],
  ['Parquet du Gabon','bois','Nkok','Estuaire','SARL',2015,15,'Production de parquet.',['parquet']],
  ['Palette du Gabon','bois','Owendo','Estuaire','SARL',2012,20,'Fabrication de palettes.',['palettes']],
  ['Charbon de Bois Gabon','bois','Libreville','Estuaire','EI',2010,5,'Production charbon de bois.',['charbon']],
  // Entreprises dans autres villes
  ['Aéroport de Mvengué','trans','Franceville','Haut-Ogooué','SA',2000,60,'Aéroport international de Mvengué.',['aéroport']],
  ['Pharmacie de Bitam','sante','Bitam','Woleu-Ntem','EI',2008,4,'Pharmacie de Bitam.',['pharmacie']],
  ['Commerce Général de Bitam','comm','Bitam','Woleu-Ntem','SARL',2010,6,'Commerce de détail Bitam.',['commerce']],
  ['Hôtel de Bitam','tour','Bitam','Woleu-Ntem','SARL',2012,8,'Hôtel de Bitam.',['hôtel']],
  ['Pharmacie de Mitzic','sante','Mitzic','Woleu-Ntem','EI',2009,4,'Pharmacie de Mitzic.',['pharmacie']],
  ['Alimentation Mitzic','comm','Mitzic','Woleu-Ntem','EI',2010,3,'Épicerie Mitzic.',['épicerie']],
  ['Pharmacie de Ndjolé','sante','Ndjolé','Moyen-Ogooué','EI',2008,4,'Pharmacie de Ndjolé.',['pharmacie']],
  ['Commerce Ndjolé','comm','Ndjolé','Moyen-Ogooué','EI',2010,3,'Commerce général Ndjolé.',['commerce']],
  ['Pharmacie d\'Okondja','sante','Okondja','Haut-Ogooué','EI',2010,4,'Pharmacie d\'Okondja.',['pharmacie']],
  ['Pharmacie de Lékoni','sante','Lékoni','Haut-Ogooué','EI',2012,3,'Pharmacie de Lékoni.',['pharmacie']],
  ['Mounana Commerce','comm','Mounana','Haut-Ogooué','EI',2008,5,'Commerce général Mounana.',['commerce']],
  ['Hotel de Lastoursville','tour','Lastoursville','Ogooué-Lolo','SARL',2010,8,'Hôtel de Lastoursville.',['hôtel']],
  ['Transport Ogooué-Lolo','trans','Koulamoutou','Ogooué-Lolo','SARL',2015,8,'Transport inter-urbain Ogooué-Lolo.',['transport']],
  ['Pharmacie de Fougamou','sante','Fougamou','Ngounié','EI',2010,3,'Pharmacie de Fougamou.',['pharmacie']],
  ['Pharmacie de Ndendé','sante','Ndendé','Ngounié','EI',2012,3,'Pharmacie de Ndendé.',['pharmacie']],
  ['Pharmacie de Gamba','sante','Gamba','Ogooué-Maritime','EI',2008,4,'Pharmacie de Gamba.',['pharmacie']],
  ['Shell Gabon Gamba','mines','Gamba','Ogooué-Maritime','SA',1990,200,'Opérations pétrolières Gamba.',['pétrole','Gamba']],
  ['Loango Eco-Lodge','tour','Gamba','Ogooué-Maritime','SARL',2010,12,'Écolodge Parc National Loango.',['écolodge','Loango']],
  ['Tourisme Ivindo','tour','Makokou','Ogooué-Ivindo','SARL',2012,6,'Tours et excursions Ivindo.',['tourisme','excursions']],
  ['Pongara Lodge','tour','Libreville','Estuaire','SARL',2015,10,'Lodge parc Pongara.',['lodge','nature']],
  ['Sette Cama Lodge','tour','Gamba','Ogooué-Maritime','SARL',2012,8,'Écolodge Sette Cama.',['écolodge']],
  ['Mikongo Primate Lodge','tour','Lopé','Ogooué-Ivindo','SARL',2008,6,'Lodge primates forêt tropicale.',['primates','écolodge']],
  ['Langoué Bai Camp','tour','Ivindo','Ogooué-Ivindo','SARL',2015,5,'Camp safari forêt d\'Ivindo.',['safari','camp']],
  // Services additionnels Libreville
  ['Agence de Voyages Arc-en-Ciel','tour','Libreville','Estuaire','SARL',2005,8,'Agence de voyages et billetterie.',['voyages','billetterie']],
  ['Voyages et Tourisme Gabon','tour','Libreville','Estuaire','SARL',2008,10,'Tours et voyages organisés.',['voyages','tours']],
  ['Gabon Visas Services','comm','Libreville','Estuaire','SARL',2012,5,'Assistance visas et documents.',['visas','services']],
  ['Pressing Express Gabon','comm','Libreville','Estuaire','SARL',2010,8,'Pressing et blanchisserie.',['pressing']],
  ['Coiffure Afrique Style','comm','Libreville','Estuaire','EI',2012,4,'Salon de coiffure.',['coiffure']],
  ['Spa Zen Libreville','tour','Libreville','Estuaire','SARL',2016,6,'Spa et soins du corps.',['spa','bien-être']],
  ['Auto-Lavage Express','comm','Libreville','Estuaire','EI',2015,5,'Lavage automobile.',['lavage','auto']],
  ['Gabon Vet','sante','Libreville','Estuaire','SARL',2010,8,'Clinique vétérinaire.',['vétérinaire']],
  ['Pompes Funèbres du Gabon','comm','Libreville','Estuaire','SA',2000,30,'Services funéraires.',['funéraire']],
  ['Sécurité Incendie Gabon','comm','Libreville','Estuaire','SARL',2008,15,'Extincteurs et sécurité incendie.',['incendie','sécurité']],
];
export const BATCH3_ENTERPRISES:AnnuaireEnterprise[]=D.map((e,i)=>mk(e,i));
